Repository blitz-js/blitz, pull requests merged in 2020-06, with the labels that each got.

#592 Fix `blitz console` loading freeze
  packages/repl/src/repl.ts
  packages/repl/src/utils/load-blitz.ts
  packages/repl/test/repl.test.ts
Labels: status/in-review

#599 Allow function config in withBlitz
  packages/server/src/with-blitz.ts
  packages/server/test/with-blitz.test.ts
Labels: status/in-review

#609 Fix Glob in GUI for Windows
  packages/gui/db/gui.db
  packages/gui/utils/getDirMtime.ts
Labels: status/in-review

#546 Add ability to prefetch query data
  examples/store/app/admin/pages/admin/products/index.tsx
  packages/core/src/rpc.ts
  packages/core/src/use-infinite-query.ts
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
  packages/core/src/utils/index.ts
  packages/core/test/rpc.test.ts
  packages/server/src/stages/rpc/index.ts
Labels: status/in-review

#601 Do not warn on nested route errors
  packages/file-pipeline/src/index.ts
  packages/file-pipeline/src/types.ts
  packages/server/src/stages/pages/errors.ts
  packages/server/src/stages/pages/find-duplicates.test.ts
  packages/server/src/stages/pages/index.ts
  packages/server/src/stages/pages/pages-path-transformer.test.ts
  packages/server/src/stages/pages/pages.test.ts
  packages/server/src/stages/utils.ts
Labels: status/in-review

#615 Add universal stream abstraction
  packages/file-pipeline/src/events.ts
  packages/file-pipeline/src/helpers/enrich-files.ts
  packages/file-pipeline/src/helpers/file-cache.ts
  packages/file-pipeline/src/helpers/unlink.ts
  packages/file-pipeline/src/helpers/work-optimizer.ts
  packages/file-pipeline/src/helpers/writer.ts
  packages/file-pipeline/src/index.ts
  packages/file-pipeline/src/test-utils.ts
  packages/file-pipeline/src/transform.test.ts
  packages/file-pipeline/src/transform.ts
  packages/file-pipeline/src/types.ts
  packages/file-pipeline/src/utils.ts
  packages/server/src/stages/config/index.ts
  packages/server/src/stages/manifest/index.ts
  packages/server/src/stages/pages/index.ts
  packages/server/src/stages/relative/index.ts
  packages/server/src/stages/rpc/index.ts
Labels: status/in-review

#596 Add `useQuery` mutate function for updating query cache
  README.md
  examples/store/app/admin/pages/admin/products/[id].tsx
  packages/core/src/types.ts
  packages/core/src/use-infinite-query.ts
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
  packages/core/src/utils/query-cache.ts
  packages/generator/templates/page/__modelIdParam__/edit.tsx
Labels: status/in-review

#613 Fix 'blitz help' not working from global cli
  packages/cli/src/check-before-running.ts
Labels: status/in-review

#621 [GUI] Fallback to NPM when Yarn isn't installed
  packages/gui/app/mutations/createProject.ts
  packages/gui/package.json
  packages/gui/types/index.d.ts
Labels: status/in-review

#574 Add `useParams` and `useRouterQuery` hooks
  examples/store/app/admin/pages/admin/products/[id].tsx
  examples/store/app/admin/pages/admin/products/index.tsx
  examples/store/cypress/integration/admin/products/index.test.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/use-params.ts
  packages/core/src/use-router-query.ts
  packages/core/test/use-params.test.ts
Labels: status/in-review

#616 Fix ready event bug
  .github/workflows/main.yml
  packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts
  packages/file-pipeline/src/helpers/agnostic-source/fixtures/one
  packages/file-pipeline/src/helpers/agnostic-source/fixtures/two
  packages/file-pipeline/src/helpers/agnostic-source/index.ts
  packages/file-pipeline/src/helpers/idle-handler.test.ts
  packages/file-pipeline/src/helpers/idle-handler/idle-handler.test.ts
  packages/file-pipeline/src/helpers/idle-handler/index.ts
Labels: status/in-review

#567 Ensure Prisma client is generated on blitz build & blitz start
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/start.ts
  packages/cli/test/commands/build.test.ts
  packages/cli/test/commands/start.test.ts
  packages/server/src/build.ts
  packages/server/src/prod.ts
  packages/server/test/prod.test.ts
Labels: status/done

#628 Remove alpha docs and redirect to blitzjs.com
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  MANIFESTO.md
  README.md
  TUTORIAL.md
  USER_GUIDE.md
Labels: status/in-review

#74 [RFC] Blitz File Structure & Routing
  rfc-docs/02-file-structure-routing.md
Labels: kind/rfc

#73 [RFC] Blitz App Architecture
  rfc-docs/01-architecture.md
Labels: kind/rfc

#629 Add rules summary to stages README.md
  packages/server/src/stages/README.md
Labels: status/in-review

#617 Add new unit tests for file-pipeline
  packages/file-pipeline/src/helpers/idle-handler/idle-handler.test.ts
  packages/file-pipeline/src/helpers/work-optimizer/README.md
  packages/file-pipeline/src/helpers/work-optimizer/index.ts
  packages/file-pipeline/src/helpers/work-optimizer/work-optimizer.test.ts
  packages/file-pipeline/src/helpers/writer/index.ts
  packages/file-pipeline/src/helpers/writer/write.test.ts
  packages/file-pipeline/src/pipeline.ts
  packages/file-pipeline/src/transform-files/index.ts
  packages/file-pipeline/src/transform-files/transform-files.test.ts
Labels: status/in-review

#638 Rename `NextScript` to `BlitzScript`
  examples/plain-js/app/pages/_document.js
  examples/store/app/pages/_document.tsx
  examples/tailwind/app/pages/_document.tsx
  packages/core/src/index.ts
  packages/generator/templates/app/app/pages/_document.tsx
Labels: status/in-review

#608 Rewrite recipe installer framework with Ink
  package.json
  packages/cli/src/commands/install.ts
  packages/cli/test/commands/install.test.ts
  packages/generator/src/generator.ts
  packages/installer/README.md
  packages/installer/package.json
  packages/installer/src/components/branded.tsx
  packages/installer/src/components/newline.tsx
  packages/installer/src/executors/add-dependency-executor.ts
  packages/installer/src/executors/add-dependency-executor.tsx
  packages/installer/src/executors/executor.ts
  packages/installer/src/executors/executor.tsx
  packages/installer/src/executors/file-prompt.ts
  packages/installer/src/executors/file-transform-executor.ts
  packages/installer/src/executors/file-transform-executor.tsx
  packages/installer/src/executors/new-file-executor.ts
  packages/installer/src/executors/new-file-executor.tsx
  packages/installer/src/index.ts
  packages/installer/src/installer.ts
  packages/installer/src/installer.tsx
  packages/installer/src/recipe-renderer.tsx
  packages/installer/src/utils/transform.ts
  packages/installer/src/utils/use-enter-to-continue.ts
  packages/installer/src/utils/wait-for-confirmation.ts
  yarn.lock
Labels: status/in-review

#645 Only parse typescript/js files for relative paths in file-pipeline
  packages/server/src/stages/pages/pages.test.ts
  packages/server/src/stages/relative/index.ts
  packages/server/src/stages/relative/relative.test.ts
  packages/server/src/stages/stage-test-utils.ts
Labels: status/in-review

#646 Add dot option to glob
  packages/file-pipeline/src/helpers/agnostic-source/index.ts
Labels: status/in-review

#637 Add `useParam` hook
  examples/store/app/admin/pages/admin/products/[id].tsx
  packages/core/src/use-params.ts
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
Labels: status/in-review

#545 Add `blitz generate model` 🎉
  packages/cli/src/commands/generate.ts
  packages/generator/package.json
  packages/generator/src/generator.ts
  packages/generator/src/generators/model-generator.ts
  packages/generator/src/prisma/field.ts
  packages/generator/src/prisma/model.ts
  packages/generator/src/utils/pipe.ts
  packages/generator/src/utils/plurals.ts
  packages/generator/templates/app/app/pages/index.tsx
  packages/generator/test/prisma/__snapshots__/model.test.ts.snap
  packages/generator/test/prisma/field.test.ts
  packages/generator/test/prisma/model.test.ts
Labels: status/in-review

#636 Add missing re-export items from Next.js
  packages/core/src/index.ts
Labels: status/in-review

#633 Do some yarn workspace maintenance
  README.md
  package.json
  packages/blitz/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/display/package.json
  packages/file-pipeline/package.json
  packages/generator/package.json
  packages/installer/package.json
  packages/repl/package.json
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#651 Fix pipeline build error
  packages/file-pipeline/src/helpers/idle-handler/index.ts
Labels: status/in-review

#655 Update query/mutation templates for Prisma 2.0.0
  packages/generator/templates/app/package.json
  packages/generator/templates/query/get__ModelNames__.ts
Labels: status/in-review

#658 Update example apps to Prisma 2.0.0
  examples/plain-js/package.json
  examples/store/app/products/pages/products/infinite.tsx
  examples/store/app/products/pages/products/paginated.tsx
  examples/store/app/products/queries/getProducts.ts
  examples/store/app/products/queries/getProductsInfinite.ts
  examples/store/package.json
  examples/tailwind/package.json
  yarn.lock
Labels: status/in-review

#664 Sync README parts with blitzjs.com/docs/getting-started
  README.md
Labels: status/in-review

#662 Add three lint rules to catch async/await promise bugs
  .eslintrc.js
  package.json
  packages/blitz/test/todo.test.ts
  packages/core/src/rpc.ts
  packages/core/src/utils/query-cache.ts
  packages/core/test/rpc.test.ts
  packages/core/test/use-query.test.tsx
  packages/file-pipeline/src/helpers/agnostic-source/index.ts
  packages/file-pipeline/src/helpers/writer/write.test.ts
  packages/file-pipeline/src/transform.test.ts
  packages/file-pipeline/src/transform.ts
  packages/generator/src/generators/app-generator.ts
  packages/generator/src/generators/form-generator.ts
  packages/generator/src/generators/model-generator.ts
  packages/generator/src/generators/mutation-generator.ts
  packages/generator/src/generators/page-generator.ts
  packages/generator/src/generators/query-generator.ts
  packages/generator/templates/app/package.json
  packages/installer/src/executors/add-dependency-executor.tsx
  packages/installer/src/executors/file-prompt.ts
  packages/installer/src/executors/file-transform-executor.tsx
  packages/installer/src/executors/new-file-executor.tsx
  packages/installer/src/installer.tsx
  packages/repl/src/repl.ts
  packages/server/src/manifest-loader.ts
  packages/server/src/next-utils.ts
  packages/server/src/stages/relative/relative.test.ts
  packages/server/test/api-routes.test.ts
  packages/server/test/build.test.ts
  packages/server/test/dev.test.ts
  packages/server/test/prod.test.ts
  packages/server/test/rules.test.ts
  packages/server/test/vercel-now.test.ts
Labels: status/in-review

#674 Add AppProps to _app.tsx in new app template (#671)
  packages/generator/templates/app/app/pages/_app.tsx
Labels: status/in-review

#653 Add @blitzjs/config package for internal use
  MEETING_NOTES.md
  README.md
  packages/config/.gitignore
  packages/config/README.md
  packages/config/jest.config.js
  packages/config/jest.setup.js
  packages/config/package.json
  packages/config/src/index.ts
  packages/config/src/node.d.ts
  packages/config/tsconfig.json
  packages/config/tsdx.config.js
  packages/gui/app/components/CreateFileBrowserModal.tsx
  packages/gui/app/components/CreateProjectForm.tsx
  packages/gui/app/components/CreateProjectInputs.tsx
  packages/gui/app/components/CreateProjectModal.tsx
  packages/gui/app/components/CreateProjectStatus.tsx
  packages/gui/app/components/Fade.tsx
  packages/gui/app/components/FileBrowser.tsx
  packages/gui/app/components/Greeting.tsx
  packages/gui/app/components/Nav.tsx
  packages/gui/app/components/PagesModule.tsx
  packages/gui/app/components/ProjectCard.tsx
  packages/gui/app/components/ProjectHeader.tsx
  packages/gui/app/components/ProjectModules.tsx
  packages/gui/app/pages/index.tsx
  packages/gui/app/queries/getCreateProjectStatus.ts
  packages/gui/app/queries/getDirectory.ts
  packages/gui/app/queries/getProjects.ts
  yarn.lock
Labels: status/in-review

#676 Syncify getConfig method in @blitzjs/config package
  packages/config/src/index.ts
Labels: status/in-review

#679 Fix eslint warnings in GUI
  packages/gui/app/components/FileBrowser.tsx
  packages/gui/app/pages/index.tsx
  packages/gui/app/queries/getDirectory.ts
Labels: status/in-review

#680 Add spinner for Prettier formatting during 'blitz new'
  packages/generator/src/generators/app-generator.ts
Labels: status/in-review

#684 Add missing useParam import in edit templates
  packages/generator/templates/page/__modelIdParam__/edit.tsx
Labels: status/in-review

#685 Possible fix for stuck at _manifest: Debounce manifest writing
  packages/file-pipeline/src/index.ts
  packages/server/src/stages/manifest/index.ts
Labels: status/in-review

#687 Ignore all `.git` sub files and folders
  packages/file-pipeline/src/helpers/agnostic-source/index.ts
  packages/server/src/config.ts
  packages/server/test/build.test.ts
  packages/server/test/dev.test.ts
Labels: status/in-review

#659 Fix top level await in `blitz console` 🎉
  packages/blitz/bin/blitz
  packages/cli/src/commands/console.ts
Labels: status/in-review

#688 Fix typo in model genereation output
  packages/generator/src/generators/model-generator.ts
Labels: status/in-review

#652 Add HTTP Middleware 🎉
  examples/store/app/products/pages/products/ssr.tsx
  examples/store/app/products/queries/getProducts.ts
  examples/store/blitz.config.js
  package.json
  packages/core/jest.setup.js
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/middleware.test.ts
  packages/core/src/middleware.ts
  packages/core/src/rpc.ts
  packages/core/src/ssr-query.test.ts
  packages/core/src/ssr-query.ts
  packages/core/src/use-infinite-query.ts
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
  packages/core/test/rpc.test.ts
  packages/core/test/use-query.test.tsx
  packages/display/src/index.ts
  packages/generator/templates/mutation/create__ModelName__.ts
  packages/generator/templates/mutation/delete__ModelName__.ts
  packages/generator/templates/mutation/update__ModelName__.ts
  packages/generator/templates/query/get__ModelName__.ts
  packages/generator/templates/query/get__ModelNames__.ts
  packages/installer/package.json
  packages/installer/types/index.d.ts
  packages/server/package.json
  packages/server/src/rpc.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/with-blitz.ts
  packages/server/test/rpc.test.ts
  yarn.lock
Labels: status/in-review

#683 Prevent `blitz db migrate` from attempting to create new migration files in production
  packages/cli/src/commands/db.ts
  packages/cli/test/commands/db.test.ts
Labels: status/in-review

#677 Added `params` and `query` to `useRouter` and `withRouter`
  packages/core/src/index.ts
  packages/core/src/use-router.ts
  packages/core/src/with-router.tsx
Labels: status/in-review

#695 [Page template] Forward submit event from form to parent event handler
  packages/generator/templates/form/__ModelName__Form.tsx
Labels: status/in-review

#697 Maybe fix the stuck at _manifest issue: Increase stream highwatermark
  packages/file-pipeline/src/streams.ts
  packages/file-pipeline/src/transform-files/highwatermark.test.ts
Labels: status/in-review

#669 Fix page generator with custom context
  packages/cli/src/commands/generate.ts
  packages/cli/test/commands/generate.test.ts
  packages/generator/src/generators/page-generator.ts
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
  packages/generator/test/generators/page-generator.test.ts
Labels: status/in-review

#704 Fix broken CLI from error: @blitzjs/cli: Cannot find module 'react'
  examples/plain-js/package.json
  examples/store/package.json
  examples/tailwind/package.json
  lerna.json
  packages/blitz/package.json
  packages/cli/package.json
  packages/config/package.json
  packages/core/package.json
  packages/display/package.json
  packages/file-pipeline/package.json
  packages/generator/package.json
  packages/gui/package.json
  packages/installer/package.json
  packages/repl/package.json
  packages/server/package.json
  packages/server/src/rpc.ts
  yarn.lock
Labels: status/in-review

#705 Fix broken cli when using npm where global blitz version used instead of local
  examples/plain-js/package.json
  examples/store/cypress/support/index.js
  examples/store/package.json
  examples/tailwind/package.json
  lerna.json
  packages/blitz/package.json
  packages/blitz/src/bin/cli.ts
  packages/cli/package.json
  packages/config/package.json
  packages/core/package.json
  packages/display/package.json
  packages/file-pipeline/package.json
  packages/generator/package.json
  packages/generator/src/generator.ts
  packages/gui/package.json
  packages/installer/package.json
  packages/repl/package.json
  packages/server/package.json
Labels: status/in-review

#706 Various DX improvements
  examples/plain-js/.prettierignore
  examples/store/.prettierignore
  examples/tailwind/.prettierignore
  packages/core/src/middleware.ts
  packages/generator/templates/app/.prettierignore
  packages/generator/templates/app/public/logo.png
  packages/generator/templates/form/__ModelName__Form.tsx
  packages/generator/templates/mutation/create__ModelName__.ts
  packages/generator/templates/mutation/delete__ModelName__.ts
  packages/generator/templates/mutation/update__ModelName__.ts
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
  packages/generator/templates/query/get__ModelName__.ts
  packages/generator/templates/query/get__ModelNames__.ts
Labels: status/in-review

#631 Fix `blitz start -p 1234` not throwing an error if port 1234 is already in use
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/start.ts
  packages/cli/test/commands/build.test.ts
  packages/cli/test/commands/start.test.ts
  packages/server/src/config.ts
  packages/server/src/next-utils.ts
Labels: status/in-review

#708 Prevent automatic conversion of field names
  packages/generator/src/prisma/field.ts
  packages/generator/src/utils/plurals.ts
  packages/generator/test/prisma/field.test.ts
Labels: status/in-review

#711 Fix `blitz new` dependency install issue (missing dependency in @blitzjs/generator)
  packages/generator/package.json
  yarn.lock
Labels: status/in-review

#715 Support Optimistic UI Updates: Add refetch option to useQuery mutate()
  packages/core/src/utils/query-cache.ts
  packages/core/test/query-cache.test.ts
Labels: status/in-review

#716 Fix `blitz db reset` for Prisma >=2.0.0-beta.8
  packages/cli/src/commands/db.ts
Labels: status/in-review

#719 Fix middleware error handling when using `next(error)`
  packages/core/src/middleware.test.ts
  packages/core/src/middleware.ts
  packages/core/src/ssr-query.test.ts
Labels: status/in-review

#722 Fix `Router` export from 'blitz'
  packages/core/src/index.ts
Labels: status/in-review
