Repository blitz-js/blitz, pull requests merged in 2020-11, with the labels that each got.

#1411 Remove `as` prop from blitz generate page templates
  examples/plain-js/app/projects/pages/projects/[id]/edit.js
  examples/plain-js/app/projects/pages/projects/new.js
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
Labels: status/in-review

#1397 Upon `blitz new`, prompt user for upgrade if blitz version is outdated
  packages/cli/src/commands/new.ts
Labels: status/in-review

#1414 Switch to superjson for error serialization (enables using `instanceof`)
  examples/auth/app/auth/components/LoginForm.tsx
  examples/auth/app/pages/_app.tsx
  examples/auth/app/pages/ssr.tsx
  examples/auth/app/users/pages/users/index.tsx
  examples/auth/app/users/queries/getUsers.ts
  packages/core/package.json
  packages/core/src/errors.ts
  packages/core/src/rpc.ts
  packages/core/test/rpc.test.ts
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/pages/_app.tsx
  packages/server/package.json
  packages/server/src/rpc.ts
  yarn.lock
Labels: status/in-review

#1416 Fix useInfiniteQuery bug on canary where page params are empty
  examples/store/app/products/pages/products/infinite.tsx
  examples/store/cypress/integration/products.test.ts
  examples/store/db/seeds.ts
  examples/store/package.json
  packages/core/src/use-query-hooks.ts
Labels: status/in-review

#1418 Remove React imports from page templates
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
Labels: status/in-review

#1419 Fix cannot read property '_clientVersion' of undefined
  packages/server/src/stages/rpc/index.ts
Labels: status/in-review

#1422 Fix: disable useQuery on first render, when router params don't exist yet AND fix TS type for useRouter()
  packages/core/src/types.ts
  packages/core/src/use-query-hooks.ts
  packages/core/src/use-router.ts
Labels: status/in-review

#1369 Cypress test fix
  .github/workflows/main.yml
  examples/auth/app/auth/components/LoginForm.tsx
  examples/auth/app/auth/pages/login.tsx
  examples/auth/app/pages/index.tsx
  examples/auth/cypress.json
  examples/auth/cypress/integration/index.test.ts
  examples/store/cypress.json
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
Labels: status/in-review

#1430 Revert react query to 2.5.12 because of concurrent mode bugs
  .gitignore
  examples/store/package.json
  packages/core/package.json
  packages/core/src/types.ts
  packages/core/src/use-mutation.ts
  packages/core/src/use-query-hooks.ts
  packages/core/src/utils/react-query-utils.ts
  packages/core/test/react-query-utils.test.ts
  packages/core/test/use-query.test.tsx
  tsconfig.json
  yarn.lock
Labels: status/in-review

#1432 Improve error message about git and git config
  packages/server/src/parse-chokidar-rules-from-gitignore.ts
  packages/server/test/parse-chokidar-rules-from-gitignore.test.ts
Labels: status/in-review

#1442 Fix CLI cannot find module get-latest-version error
  packages/cli/src/commands/new.ts
  packages/generator/src/index.ts
Labels: status/in-review

#1444 Fix broken static pre-rendering with useQuery
  examples/auth/app/pages/index.test.tsx
  examples/auth/test/utils.tsx
  examples/store/app/admin/pages/admin/products/[id].tsx
  examples/store/app/pages/_app.tsx
  packages/core/src/use-query-hooks.ts
  packages/core/src/use-router.ts
Labels: status/in-review

#1450 Improve error message for invalid RPC requests
  packages/server/src/rpc.ts
Labels: status/in-review

#1451 (newapp) Upgrade react version to `0.0.0-experimental-4ead6b530`
  examples/auth/package.json
  examples/no-prisma/package.json
  examples/plain-js/package.json
  examples/store/package.json
  packages/generator/templates/app/package.json
  packages/installer/package.json
  yarn.lock
Labels: status/in-review

#1453 Fix infinite loop with multiple tabs open
  examples/auth/app/users/pages/users/index.tsx
  packages/core/src/public-data-store.ts
Labels: status/in-review

#1458 Add Fauna Example
  README.md
  examples/fauna/.env
  examples/fauna/.eslintrc.js
  examples/fauna/.gitignore
  examples/fauna/.npmrc
  examples/fauna/.prettierignore
  examples/fauna/README.md
  examples/fauna/app/auth/auth-utils.ts
  examples/fauna/app/auth/components/LoginForm.tsx
  examples/fauna/app/auth/components/SignupForm.tsx
  examples/fauna/app/auth/mutations/login.ts
  examples/fauna/app/auth/mutations/logout.ts
  examples/fauna/app/auth/mutations/signup.ts
  examples/fauna/app/auth/pages/login.tsx
  examples/fauna/app/auth/pages/signup.tsx
  examples/fauna/app/auth/validations.ts
  examples/fauna/app/components/.keep
  examples/fauna/app/components/Form.tsx
  examples/fauna/app/components/LabeledTextField.tsx
  examples/fauna/app/hooks/useCurrentUser.ts
  examples/fauna/app/layouts/.keep
  examples/fauna/app/layouts/Layout.tsx
  examples/fauna/app/pages/404.tsx
  examples/fauna/app/pages/_app.tsx
  examples/fauna/app/pages/_document.tsx
  examples/fauna/app/pages/index.test.tsx
  examples/fauna/app/pages/index.tsx
  examples/fauna/app/users/queries/getCurrentUser.ts
  examples/fauna/babel.config.js
  examples/fauna/blitz.config.js
  examples/fauna/db/index.ts
  examples/fauna/db/schema.graphql
  examples/fauna/db/seeds.ts
  examples/fauna/integrations/.keep
  examples/fauna/jest.config.js
  examples/fauna/package.json
  examples/fauna/public/favicon.ico
  examples/fauna/public/logo.png
  examples/fauna/test/.keep
  examples/fauna/test/__mocks__/fileMock.js
  examples/fauna/test/setup.ts
  examples/fauna/test/utils.tsx
  examples/fauna/tsconfig.json
  examples/fauna/types.ts
  examples/fauna/utils/.keep
  packages/cli/src/commands/db.ts
  yarn.lock
Labels: status/in-review

#1464 Fix initial migration for new apps is not included in the initial git commit
  packages/cli/src/commands/new.ts
  packages/generator/src/generators/app-generator.ts
Labels: status/in-review

#159 Only run Lambda warm-up HEAD requests when target is serverless
  examples/auth/test/utils.tsx
  examples/fauna/.eslintrc.js
  examples/fauna/app/auth/components/LoginForm.tsx
  examples/fauna/app/auth/components/SignupForm.tsx
  examples/fauna/app/auth/pages/login.tsx
  examples/fauna/app/auth/pages/signup.tsx
  examples/fauna/app/components/Form.tsx
  examples/fauna/app/components/LabeledTextField.tsx
  examples/fauna/app/pages/_document.tsx
  examples/fauna/app/pages/index.test.tsx
  examples/fauna/test/utils.tsx
  packages/cli/src/commands/start.ts
  packages/core/src/rpc.ts
  packages/core/src/utils/tokens.test.ts
  packages/core/test/rpc.test.ts
  packages/server/src/index.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/test/vercel-now.test.ts
  rfc-docs/03-session-management.md
Labels: status/in-progress

#1466 Update Chakra UI Recipe for 1.0
  recipes/chakra/index.ts
Labels: status/in-review

#1469 Added Flavio as L1 Maintainer to the README
  README.md
Labels: status/in-review

#1463 Fix image component external domains not working in production
  packages/server/src/build.ts
  packages/server/src/prod.ts
Labels: status/in-review

#1477 Fix issue where `blitz start --production` rebuilds during deployment
  packages/server/src/build-hash.ts
Labels: status/in-review

#1476 Remove undocumented `hasOne` and `hasMany` options from `blitz generate model`
  packages/cli/src/commands/generate.ts
  packages/generator/src/prisma/field.ts
  packages/generator/test/prisma/field.test.ts
Labels: status/in-review

#1423 Add new `Image` component from Next.js 10
  packages/cli/jest.setup.js
  packages/cli/package.json
  packages/core/src/index.ts
  packages/server/jest.config.js
  packages/server/jest.setup.js
  packages/server/package.json
Labels: status/in-review

#1456 Fix ability to import from pages, API routes, and queries/mutations
  examples/auth/app/auth/auth-utils.ts
  examples/auth/app/auth/components/LoginForm.tsx
  examples/auth/app/auth/mutations/login.ts
  examples/auth/app/auth/mutations/signup.ts
  examples/auth/app/auth/pages/signup.tsx
  examples/auth/app/auth/validations.ts
  examples/store/app/admin/api/users.ts
  examples/store/app/admin/pages/admin/products/index.tsx
  examples/store/app/products/pages/products/index.tsx
  examples/store/app/products/queries/getProducts.ts
  examples/store/cypress/integration/admin/products/index.test.ts
  examples/store/cypress/integration/products.test.ts
  packages/core/src/rpc.ts
  packages/server/src/stages/index.ts
  packages/server/src/stages/relative/pattern-relative-import.test.ts
  packages/server/src/stages/rewrite-imports/index.ts
  packages/server/src/stages/rewrite-imports/rewrite-imports.test.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/with-blitz.ts
Labels: status/in-review

#1496 Fix an import edgecase by only rewriting relative paths imports for files in special folders (patch)
  packages/server/src/stages/relative/index.ts
  packages/server/src/stages/relative/relative-paths.test.ts
  packages/server/src/stages/relative/relative.test.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1498 (newapp) Add `.next` and `.blitz` to `.prettierignore`
  packages/generator/templates/app/.prettierignore
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1494 Cleanup unused args in server
  packages/server/src/build.ts
  packages/server/src/dev.ts
  packages/server/src/prod.ts
  packages/server/test/prod.test.ts
Labels: status/in-review

#1493 Fix File not found with singular glob
  packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts
  packages/file-pipeline/src/helpers/agnostic-source/index.ts
Labels: status/in-review

#1474 Change `useParam()` to always return `undefined` if param doesn’t exist
  packages/core/src/use-params.ts
  packages/core/test/use-params.test.ts
Labels: status/in-review

#1499 Fix broken css modules imports on canary (patch)
  examples/store/app/pages/index.module.css
  examples/store/app/pages/index.tsx
  packages/server/src/stages/pages/index.ts
  packages/server/src/stages/pages/pages-path-transformer.test.ts
Labels: status/in-review

#1446 Automatically clear `.blitz` cache when you change blitz versions
  packages/server/src/blitz-version.ts
  packages/server/src/dev.ts
  packages/server/test/api-routes.test.ts
  packages/server/test/dev.test.ts
  packages/server/test/rules.test.ts
Labels: status/in-review

#1518 Update `blitz generate` templates for Prisma 2.12.0 compatibility
  examples/auth/app/users/queries/getUser.ts
  examples/auth/package.json
  packages/generator/templates/mutation/create__ModelName__.ts
  packages/generator/templates/mutation/delete__ModelName__.ts
  packages/generator/templates/mutation/update__ModelName__.ts
  packages/generator/templates/queries/get__ModelName__.ts
  packages/generator/templates/queries/get__ModelNames__.ts
  yarn.lock
Labels: status/in-review

#1515 Fix lint warnings
  packages/server/src/stages/rewrite-imports/index.ts
  packages/server/src/stages/rewrite-imports/rewrite-imports.test.ts
Labels: status/in-review

#1505 Forgot password spelling errors
  packages/generator/templates/app/app/auth/auth-utils.ts
  packages/generator/templates/app/app/auth/mutations/forgotPassword.ts
  packages/generator/templates/app/app/auth/mutations/resetPassword.ts
  packages/generator/templates/app/db/schema.prisma
Labels: status/in-review

#1510 Fix bug where `blitz db seed` will error silently
  packages/cli/src/commands/db.ts
Labels: status/in-review

#1486 (recipe) Update tailwind recipe to v2
  recipes/tailwind/index.ts
  recipes/tailwind/templates/config/postcss.config.js
  recipes/tailwind/templates/config/tailwind.config.js
  recipes/tailwind/templates/styles/styles/button.css
  recipes/tailwind/templates/styles/styles/index.css
Labels: status/in-review

#1491 Change `useParam` / `useParams` to always return `undefined` for empty/invalid values instead of `""` and `NaN` (patch)
  packages/core/src/types.ts
  packages/core/src/use-params.ts
  packages/core/test/use-params.test.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1525 Change `prisma.findOne` to `prisma.findFirst` for Prisma 2.12 compatibility
  examples/auth/app/auth/auth-utils.ts
  examples/auth/app/users/queries/getCurrentUser.ts
  examples/auth/app/users/queries/getUser.ts
  examples/plain-js/app/projects/queries/getProject.js
  examples/store/app/products/queries/getProduct.ts
  packages/generator/templates/app/app/auth/auth-utils.ts
  packages/generator/templates/app/app/users/queries/getCurrentUser.ts
  packages/server/src/supertokens.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1527 Fix to allow for unicode chars in session data
  packages/core/package.json
  packages/core/src/utils/tokens.test.ts
  packages/core/src/utils/tokens.ts
  packages/server/src/supertokens.test.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#1533 fix: add postcss to tailwind recipe
  recipes/tailwind/index.ts
Labels: status/in-review

#1532 Fix tree shaking for imports from queries/mutations
  examples/store/app/products/queries/getProducts.ts
  examples/store/assert-tree-shaking-works.js
  examples/store/package.json
  packages/server/src/stages/rewrite-imports/index.ts
  packages/server/src/stages/rewrite-imports/rewrite-imports.test.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/with-blitz.ts
Labels: status/in-review

#1534 Fix blitz compiler to ignore gitignored files during processing
  packages/file-pipeline/package.json
  packages/file-pipeline/src/micromatch.d.ts
  packages/file-pipeline/src/pipeline.ts
  packages/file-pipeline/src/transform-files/index.test.ts
  yarn.lock
Labels: status/in-review

#1541 Fix a flaky file-pipeline test (meta)
  packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1538 Add a second css module integration test (meta)
  examples/store/app/products/components/ProductForm.module.scss
  examples/store/app/products/components/ProductForm.tsx
  examples/store/package.json
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1542 Add yalc for testing blitz locally (meta)
  package.json
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1547 Fix regression in 0.26.1 if you have a `test` folder inside `app/` (patch)
  packages/file-pipeline/package.json
  packages/file-pipeline/src/pipeline.ts
  packages/file-pipeline/src/transform-files/index.test.ts
  packages/server/src/config.ts
  yarn.lock
Labels: status/in-review

#1548 Another try at fixing flaky windows test (meta)
  packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts
Labels: status/in-review

#1549 Change `auth-utils.ts` to be side-effect free (newapp)
  packages/generator/templates/app/app/auth/auth-utils.ts
Labels: status/in-review

#1551 Add log level option to `blitz.config.js`
  examples/auth/app/pages/index.tsx
  examples/auth/app/users/queries/getUser.ts
  examples/auth/blitz.config.js
  packages/blitz/package.json
  packages/config/package.json
  packages/core/package.json
  packages/core/src/invoke.ts
  packages/core/src/middleware.ts
  packages/display/package.json
  packages/display/src/index.ts
  packages/file-pipeline/package.json
  packages/server/package.json
  packages/server/src/dev.ts
  packages/server/src/rpc.ts
Labels: status/in-review

#1552 Fix message in the `blitz generate pages` edit page
  packages/generator/templates/page/__modelIdParam__/edit.tsx
Labels: status/in-review
