Repository blitz-js/blitz, pull requests merged in 2020-05, with the labels that each got.

#396 Fix `blitz new` on Linux (fromEntries/eslint-plugin error)
  packages/cli/src/utils/get-latest-version.ts
  packages/cli/test/commands/new.test.ts
Labels: status/in-review

#342 Improve error message for api routes in wrong folder
  packages/server/src/synchronizer/pipeline/rules/pages/index.ts
Labels: scope/cli, status/in-review

#393 fix(server): force forward slashes in absolute imports
  packages/server/package.json
  packages/server/src/synchronizer/pipeline/rules/relative/index.ts
  packages/server/src/synchronizer/pipeline/rules/relative/relative-paths.test.ts
Labels: scope/server, status/in-review

#406 Fix fetchRemote dev script to be sh compatible
  scripts/fetchRemote.sh
Labels: kind/feature-change, status/in-progress

#381 Fix postcss purge routes on Tailwind example
  examples/tailwind/tailwind.config.js
Labels: status/in-review

#419 Contributing.md: Add node-pty troubleshooting for WSL
  CONTRIBUTING.md
Labels: os/windows, status/in-review

#366 Fix additional lint rules
  .eslintrc.js
  packages/blitz/package.json
  packages/cli/package.json
  packages/cli/src/command.ts
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/console.ts
  packages/cli/src/commands/db.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/commands/help.ts
  packages/cli/src/commands/new.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/test.ts
  packages/cli/src/errors/prompt-aborted.ts
  packages/cli/test/commands/build.test.ts
  packages/cli/test/commands/console.test.ts
  packages/cli/test/commands/db.test.ts
  packages/cli/test/commands/new.test.ts
  packages/cli/test/commands/start.test.ts
  packages/cli/test/commands/test.test.ts
  packages/generator/src/conflict-checker.ts
  packages/generator/src/errors/prompt-aborted.ts
  packages/generator/src/generator.ts
  packages/generator/src/generators/app-generator.ts
  packages/generator/src/generators/model-generator.ts
  packages/generator/src/generators/mutation-generator.ts
  packages/generator/src/generators/page-generator.ts
  packages/generator/src/generators/query-generator.ts
  packages/server/src/ci-log.ts
  packages/server/src/config.ts
  packages/server/src/index.ts
  packages/server/src/parse-gitignore.d.ts
  packages/server/src/synchronizer/display.ts
  packages/server/src/synchronizer/errors.ts
  packages/server/src/synchronizer/index.ts
  packages/server/src/synchronizer/pipeline/helpers/agnostic-source.ts
  packages/server/src/synchronizer/pipeline/helpers/enrich-files.ts
  packages/server/src/synchronizer/pipeline/helpers/file-cache.ts
  packages/server/src/synchronizer/pipeline/helpers/idle-handler.test.ts
  packages/server/src/synchronizer/pipeline/helpers/idle-handler.ts
  packages/server/src/synchronizer/pipeline/helpers/work-optimizer.ts
  packages/server/src/synchronizer/pipeline/index.ts
  packages/server/src/synchronizer/pipeline/rules/config/index.ts
  packages/server/src/synchronizer/pipeline/rules/manifest/index.ts
  packages/server/src/synchronizer/pipeline/rules/pages/index.ts
  packages/server/src/synchronizer/pipeline/rules/relative/index.ts
  packages/server/src/synchronizer/pipeline/rules/rpc/index.ts
  packages/server/src/synchronizer/pipeline/rules/write/index.ts
  packages/server/src/with-blitz.ts
  packages/server/test/dev.test.ts
  packages/server/test/with-blitz.test.ts
Labels: status/in-review

#399 Initialize git before app generate to properly set up husky hooks
  packages/generator/package.json
  packages/generator/src/generators/app-generator.ts
  packages/generator/test/generators/app-generator.test.ts
Labels: kind/bug, scope/cli, status/in-progress, status/in-review

#433 fix(generator): enable absolute path resolution in JS projects
  packages/generator/src/generators/app-generator.ts
  packages/generator/templates/app/jsconfig.json
Labels: scope/core, scope/server, status/in-progress

#413 Adds --port and --hostname to blitz start and dev commands
  README.md
  TUTORIAL.md
  examples/store/package.json
  examples/tailwind/tailwind.config.js
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/start.ts
  packages/cli/test/commands/build.test.ts
  packages/cli/test/commands/start.test.ts
  packages/core/package.json
  packages/server/package.json
  packages/server/src/config.ts
  packages/server/src/dev.ts
  packages/server/src/next-utils.ts
  packages/server/src/prod.ts
  packages/server/test/api-routes.test.ts
  packages/server/test/build.test.ts
  packages/server/test/dev.test.ts
  packages/server/test/rules.test.ts
  packages/server/test/vercel-now.test.ts
  yarn.lock
Labels: kind/feature-change, scope/cli, scope/server, status/in-review

#429 Fix file path in TUTORIAL
  TUTORIAL.md
Labels: kind/bug, scope/server, status/in-review

#456 Update maintainers on allcontributors
  .all-contributorsrc
  README.md
Labels: status/in-review

#449 Test: Add RPC tests
  package.json
  packages/core/jest.setup.js
  packages/core/test/rpc.test.ts
  packages/core/test/todo.test.ts
  packages/server/test/rpc.test.ts
  yarn.lock
Labels: status/in-review

#450 Update react-query to 1.3.3
  packages/core/package.json
  yarn.lock
Labels: kind/bug, status/in-review

#451 Fix RPC routes on Windows
  packages/server/src/synchronizer/pipeline/rules/rpc/index.ts
  packages/server/src/with-blitz.ts
  packages/server/test/with-blitz.test.ts
Labels: status/in-review

#474 Allow blitz in both dependencies and dev dependencies
  packages/cli/src/utils/is-blitz-root.ts
Labels: status/in-review

#434 Add base infrastructure for `blitz install`
  .github/CODEOWNERS
  packages/blitz/package.json
  packages/cli/package.json
  packages/cli/src/commands/install.ts
  packages/generator/src/conflict-checker.ts
  packages/generator/src/index.ts
  packages/installer/.gitignore
  packages/installer/README.md
  packages/installer/jest.config.js
  packages/installer/package.json
  packages/installer/src/executors/add-dependency-executor.ts
  packages/installer/src/executors/executor.ts
  packages/installer/src/executors/file-prompt.ts
  packages/installer/src/executors/file-transform-executor.ts
  packages/installer/src/executors/new-file-executor.ts
  packages/installer/src/index.ts
  packages/installer/src/installer.ts
  packages/installer/src/transforms/add-import.ts
  packages/installer/src/transforms/index.ts
  packages/installer/src/utils/paths.ts
  packages/installer/src/utils/transform.ts
  packages/installer/src/utils/wait-for-confirmation.ts
  packages/installer/test/transforms/__snapshots__/add-import.test.ts.snap
  packages/installer/test/transforms/add-import.test.ts
  packages/installer/test/tsconfig.json
  packages/installer/test/utils/paths.test.ts
  packages/installer/tsconfig.json
  packages/server/src/log.ts
  yarn.lock
Labels: kind/feature-change, scope/core, status/in-review

#368 ci: run tests on both Windows and Ubuntu
  .gitattributes
  .github/workflows/main.yml
  packages/cli/jest.config.js
  prettier.config.js
Labels: status/in-review

#479 Pin react experimental version & fix graceful fallback for prisma version
  packages/generator/src/utils/fetch-latest-version-for.ts
  packages/generator/templates/app/package.json
Labels: status/in-review

#480 Remove blitz db migrate from new app template build script
  USER_GUIDE.md
  packages/generator/templates/app/package.json
Labels: status/in-review

#482 Remove JS instructions and flag until we get bugs fixed (#407)"
  TUTORIAL.md
  USER_GUIDE.md
  packages/cli/src/commands/new.ts
Labels: status/in-review

#481 Fix blitz new --js not working in monorepo
  examples/store/cypress/integration/products.test.ts
  packages/cli/src/commands/console.ts
  packages/cli/src/commands/generate.ts
  yarn.lock
Labels: scope/cli, scope/examples, status/in-review

#484 Add Fauna as a bronze sponsor 🎉
  BACKERS.md
  README.md
  assets/Fauna_Logo_Blue.png
Labels: status/in-review

#420 Add CI step to monitor install time
  .github/checkInstallTime.js
  .github/workflows/main.yml
Labels: kind/feature-change, priority/low, scope/server, status/assigned, status/in-review

#486 Fix typo
  packages/generator/jest.config.js
  packages/installer/jest.config.js
Labels: status/in-review

#453 Run prettier on output of `blitz generate` commands
  package.json
  packages/generator/src/generator.ts
  yarn.lock
Labels: status/in-review

#491 Support remote packages in the installer
  packages/blitz/package.json
  packages/cli/package.json
  packages/cli/src/commands/install.ts
  packages/cli/src/utils/dedent.ts
  packages/cli/test/__fixtures__/installer.ts
  packages/cli/test/commands/install.test.ts
  packages/cli/test/utils/dedent.test.ts
  packages/installer/package.json
  packages/installer/src/executors/file-transform-executor.ts
  packages/installer/src/installer.ts
  yarn.lock
Labels: status/in-review

#499 Fix blitz generate error about prettier parser
  packages/generator/src/generator.ts
  yarn.lock
Labels: status/in-review

#497 Fix 'blitz db reset' command
  packages/cli/src/commands/db.ts
Labels: status/in-review

#500 Change all dependency versions to be pinned
  .npmrc
  examples/store/package.json
  package.json
  packages/blitz/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/generator/package.json
  packages/installer/package.json
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#501 Fix git commit error during `blitz new`
  packages/generator/src/utils/fetch-latest-version-for.ts
  packages/generator/templates/app/package.json
Labels: status/in-review

#502 Fix blitz new failing because of prettier babel-ts error
  packages/generator/src/generator.ts
  packages/generator/src/generators/app-generator.ts
Labels: status/in-review

#504 Add Jack Clancy (@jclancy93) and Ivan Medina (@ivandevp) as L1 mainta…
  .all-contributorsrc
  README.md
Labels: status/in-review

#454 Fix some node v10 compatibility issues
  package.json
  packages/cli/package.json
  packages/cli/src/commands/console.ts
  packages/cli/test/commands/console.test.ts
  packages/cli/test/commands/new.test.ts
  packages/cli/tsconfig.json
  packages/generator/src/utils/fetch-latest-version-for.ts
  yarn.lock
Labels: status/in-review

#476 Enable JavaScript projects
  packages/server/package.json
  packages/server/src/build.ts
  packages/server/src/config.ts
  packages/server/src/dev.ts
  packages/server/src/synchronizer/events.ts
  packages/server/src/synchronizer/index.ts
  packages/server/src/synchronizer/pipeline/index.ts
  packages/server/src/synchronizer/pipeline/rules/typescript/index.ts
  packages/server/src/synchronizer/types.ts
  packages/server/test/dev.test.ts
  yarn.lock
Labels: status/in-review

#498 Update Next.js to 9.4! (requires react 0.0.0-experimental-33c3af284)
  examples/store/package.json
  examples/tailwind/package.json
  package.json
  packages/generator/templates/app/package.json
  packages/installer/package.json
  packages/server/package.json
  packages/server/src/with-blitz.ts
  packages/server/test/with-blitz.test.ts
  yarn.lock
Labels: status/in-review

#506 Make a few cleanups to guides and templates
  TUTORIAL.md
  USER_GUIDE.md
  packages/generator/templates/page/__id__.tsx
  packages/generator/templates/page/__id__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
Labels: status/in-review

#493 🚀 Add context path option to `blitz generate`
  packages/cli/src/commands/generate.ts
  packages/cli/test/commands/generate.test.ts
  packages/generator/src/generator.ts
  packages/generator/src/generators/mutation-generator.ts
  packages/generator/src/generators/page-generator.ts
  packages/generator/src/generators/query-generator.ts
Labels: status/in-review

#507 Add a plain-js example and build it in our tests
  examples/plain-js/.babelrc.js
  examples/plain-js/.eslintrc.js
  examples/plain-js/.gitignore
  examples/plain-js/.npmrc
  examples/plain-js/.prettierignore
  examples/plain-js/README.md
  examples/plain-js/app/components/.keep
  examples/plain-js/app/components/ErrorBoundary.js
  examples/plain-js/app/layouts/.keep
  examples/plain-js/app/pages/_app.js
  examples/plain-js/app/pages/_document.js
  examples/plain-js/app/pages/index.js
  examples/plain-js/app/projects/mutations/createProject.js
  examples/plain-js/app/projects/mutations/deleteProject.js
  examples/plain-js/app/projects/mutations/updateProject.js
  examples/plain-js/app/projects/pages/projects/[id].js
  examples/plain-js/app/projects/pages/projects/[id]/edit.js
  examples/plain-js/app/projects/pages/projects/index.js
  examples/plain-js/app/projects/pages/projects/new.js
  examples/plain-js/app/projects/queries/getProject.js
  examples/plain-js/app/projects/queries/getProjects.js
  examples/plain-js/blitz.config.js
  examples/plain-js/db/index.js
  examples/plain-js/db/migrations/.keep
  examples/plain-js/db/migrations/20200514183443/README.md
  examples/plain-js/db/migrations/20200514183443/schema.prisma
  examples/plain-js/db/migrations/20200514183443/steps.json
  examples/plain-js/db/migrations/migrate.lock
  examples/plain-js/db/schema.prisma
  examples/plain-js/integrations/.keep
  examples/plain-js/jobs/.keep
  examples/plain-js/jsconfig.json
  examples/plain-js/package.json
  examples/plain-js/public/favicon.ico
  examples/plain-js/public/logo.png
  examples/plain-js/utils/.keep
  examples/plain-js/yarn.lock
Labels: status/in-review

#510 Revert JS server pipeline rule
  examples/plain-js/package.json
  packages/server/package.json
  packages/server/src/build.ts
  packages/server/src/config.ts
  packages/server/src/dev.ts
  packages/server/src/synchronizer/events.ts
  packages/server/src/synchronizer/index.ts
  packages/server/src/synchronizer/pipeline/index.ts
  packages/server/src/synchronizer/pipeline/rules/typescript/index.ts
  packages/server/src/synchronizer/types.ts
  packages/server/test/dev.test.ts
  yarn.lock
Labels: status/in-review

#511 Remove typescript-eslint version override for blitz new
  packages/generator/src/utils/fetch-latest-version-for.ts
  packages/generator/templates/app/package.json
  yarn.lock
Labels: status/in-review

#512 Update fork sync script to add upstream remote
  CONTRIBUTING.md
Labels: status/in-review

#518 Add instructions to deploy to Render.com to the USER_GUIDE
  USER_GUIDE.md
Labels: status/in-review

#522 Fix oclif hook id bug
  README.md
  packages/cli/package.json
  packages/cli/src/check-before-running.ts
Labels: status/in-review

#514 Ensure same prisma client is being used on hot reload
  examples/plain-js/db/index.js
  examples/store/db/index.ts
  examples/tailwind/db/index.ts
  packages/generator/templates/app/db/index.ts
Labels: status/in-review

#524 Adds a failure message if the cli compilation isn't complete
  packages/blitz/bin/blitz
Labels: status/in-review

#527 Upgrade Next.js to 9.4.1
  package.json
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#526 BREAKING: Change useQuery() to require second argument
  examples/plain-js/app/projects/pages/projects/index.js
  examples/store/app/admin/pages/admin/products/index.tsx
  examples/store/app/pages/_app.tsx
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
  packages/generator/templates/page/index.tsx
Labels: status/in-review

#534 Update Next to 9.4.2
  package.json
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#535 Fix bug in installer package with log imports
  packages/installer/src/executors/add-dependency-executor.ts
  packages/installer/src/executors/executor.ts
  packages/installer/src/executors/file-transform-executor.ts
  packages/installer/src/executors/new-file-executor.ts
  packages/installer/src/installer.ts
Labels: status/in-review

#532 Update Render deployment instructions in USER_GUIDE
  USER_GUIDE.md
Labels: status/in-review

#548 Improve JSON readability on generated show page
  packages/generator/templates/page/__modelIdParam__.tsx
Labels: status/in-review

#521 Add meta and assets packages
  packages/assets/README.md
  packages/assets/favicons/android-chrome-192x192.png
  packages/assets/favicons/android-chrome-512x512.png
  packages/assets/favicons/apple-touch-icon.png
  packages/assets/favicons/favicon-16x16.png
  packages/assets/favicons/favicon-32x32.png
  packages/assets/favicons/safari-pinned-tab.svg
  packages/assets/favicons/site.webmanifest
  packages/meta/.gitignore
  packages/meta/README.md
  packages/meta/package.json
  packages/meta/src/index.tsx
  packages/meta/test/__snapshots__/index.tsx.snap
  packages/meta/test/index.tsx
  packages/meta/tsconfig.json
  yarn.lock
Labels: kind/feature-change, status/in-review

#544 Make missing blitz db command logs clearer
  packages/cli/src/commands/db.ts
Labels: status/in-review

#551 Fix typos
  CONTRIBUTING.md
  examples/store/app/products/pages/products/index.tsx
  packages/blitz/bin/blitz
  packages/cli/src/index.ts
  packages/cli/src/utils/load-blitz.ts
  packages/server/register/launch-editor.js
Labels: status/in-review

#487 Add support for Dependent Queries to useQuery and usePaginatedQuery
  README.md
  examples/store/app/products/pages/products/paginated.tsx
  examples/store/db/index.ts
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
  packages/core/test/use-query.test.tsx
  yarn.lock
Labels: status/in-progress

#547 Fix some dependency install warnings
  package.json
  packages/core/package.json
  packages/server/package.json
  packages/server/src/synchronizer/pipeline/helpers/agnostic-source.ts
  yarn.lock
Labels: status/in-review

#561 Remove the unused jobs folder from the new app template
  packages/generator/templates/app/jobs/.keep
Labels: status/in-review

#563 Tiny refactor to new app template's index page
  packages/generator/templates/app/app/pages/index.tsx
Labels: status/in-review

#537 Fix error in types for generated queries
  examples/store/app/products/mutations/createProduct.ts
  examples/store/app/products/mutations/deleteProduct.ts
  examples/store/app/products/mutations/updateProduct.ts
  examples/store/app/products/pages/products/[handle].tsx
  examples/store/app/products/pages/products/index.tsx
  examples/store/app/products/pages/products/ssr.tsx
  examples/store/app/products/queries/getProduct.ts
  examples/store/app/products/queries/getProducts.ts
  packages/generator/templates/query/get__ModelName__.ts
  packages/generator/templates/query/get__ModelNames__.ts
Labels: status/in-review

#568 Add studio pkg.json script to new app template
  packages/generator/templates/app/package.json
Labels: status/in-review

#571 Add husky git hooks for yarn install when changing branches
  package.json
Labels: status/in-review

#565 Use previous build for `blitz start --production` if up-to-date
  packages/server/package.json
  packages/server/src/build-hash.ts
  packages/server/src/build.ts
  packages/server/src/folder-hash.d.ts
  packages/server/src/prod.ts
  packages/server/test/build.test.ts
  packages/server/test/prod.test.ts
  packages/server/test/vercel-now.test.ts
  yarn.lock
Labels: status/in-review

#576 Upgrade next to 9.4.4 version
  package.json
  packages/server/package.json
  yarn.lock
Labels: status/done

#580 Fix `examples/store` code style issues
  examples/store/.eslintrc.js
  examples/store/app/admin/pages/admin/index.tsx
  examples/store/app/admin/pages/admin/products/[id].tsx
  examples/store/app/admin/pages/admin/products/new.tsx
  examples/store/app/components/ErrorBoundary.tsx
  examples/store/app/pages/_document.tsx
  examples/store/app/pages/index.tsx
  examples/store/app/products/components/ProductForm.tsx
  examples/store/blitz.config.js
  examples/store/cypress/integration/admin/index.test.ts
  examples/store/cypress/integration/admin/products/edit.test.ts
  examples/store/cypress/integration/admin/products/helper.ts
  examples/store/cypress/integration/admin/products/index.test.ts
  examples/store/cypress/integration/admin/products/new.test.ts
  examples/store/cypress/integration/index.test.ts
  examples/store/cypress/integration/products.test.ts
  examples/store/cypress/support/index.js
Labels: status/in-review

#584 Tidy up tests in server
  packages/server/test/api-routes.test.ts
  packages/server/test/build.test.ts
  packages/server/test/dev.test.ts
  packages/server/test/prod.test.ts
  packages/server/test/rules.test.ts
  packages/server/test/utils/multi-mock.ts
  packages/server/test/vercel-now.test.ts
Labels: status/in-review

#589 Extract out display package
  packages/cli/package.json
  packages/cli/src/commands/console.ts
  packages/cli/src/commands/db.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/commands/new.ts
  packages/display/.gitignore
  packages/display/README.md
  packages/display/package.json
  packages/display/src/index.test.ts
  packages/display/src/index.ts
  packages/display/tsconfig.json
  packages/generator/package.json
  packages/generator/src/generator.ts
  packages/generator/src/generators/app-generator.ts
  packages/generator/src/utils/get-latest-version.ts
  packages/generator/test/generators/app-generator.test.ts
  packages/installer/package.json
  packages/installer/src/executors/add-dependency-executor.ts
  packages/installer/src/executors/executor.ts
  packages/installer/src/executors/file-transform-executor.ts
  packages/installer/src/executors/new-file-executor.ts
  packages/installer/src/installer.ts
  packages/server/package.json
  packages/server/src/index.ts
  packages/server/src/rpc.ts
  packages/server/src/synchronizer/display.ts
  packages/server/src/synchronizer/errors.ts
Labels: status/in-review

#590 Add `useInfiniteQuery` hook
  examples/store/app/pages/index.tsx
  examples/store/app/products/pages/products/infinite.tsx
  examples/store/app/products/queries/getProductsInfinite.ts
  packages/core/src/index.ts
  packages/core/src/use-infinite-query.ts
Labels: status/in-review

#593 Fix queries when Prisma isn't being used
  packages/server/src/synchronizer/pipeline/rules/rpc/index.ts
Labels: status/in-review
