Repository blitz-js/blitz, pull requests merged in 2020-12, with the labels that each got.

#1559 Update Emotion recipe to v11
  recipes/emotion/index.ts
  recipes/emotion/templates/styles/styles/index.tsx
Labels: status/in-review

#1562 Fix broken `blitz install`
  packages/installer/package.json
Labels: status/in-review

#1563 (newapp) Change `useCurrentUser` hook to not use `useSession` (fixes UX)
  examples/auth/app/hooks/useCurrentUser.ts
  examples/fauna/app/hooks/useCurrentUser.ts
  packages/generator/templates/app/app/hooks/useCurrentUser.ts
Labels: status/in-review

#1571 Fix broken `blitz install`
  packages/config/src/index.ts
  packages/core/package.json
  packages/display/package.json
  packages/file-pipeline/package.json
  packages/installer/package.json
  packages/server/package.json
  packages/server/test/api-routes.test.ts
  packages/server/test/build.test.ts
  packages/server/test/dev.test.ts
  packages/server/test/prod.test.ts
  packages/server/test/rules.test.ts
  packages/server/test/with-blitz.test.ts
  yarn.lock
Labels: status/in-review

#1574 Fix module not found issues by moving isomorphic resolver imports behind experimental flag
  examples/auth/blitz.config.js
  examples/store/blitz.config.js
  packages/config/src/index.ts
  packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts
  packages/server/src/with-blitz.ts
Labels: status/in-review

#1554 Fix `blitz generate` folder names to always be kebab-case
  packages/generator/src/generators/form-generator.ts
  packages/generator/src/generators/mutation-generator.ts
  packages/generator/src/generators/queries-generator.ts
  packages/generator/src/generators/query-generator.ts
Labels: status/in-review

#1366 Add Theme UI recipe (including MDX!)
  recipes/chakra/index.ts
  recipes/tailwind/templates/config/postcss.config.js
  recipes/tailwind/templates/config/tailwind.config.js
  recipes/tailwind/templates/styles/styles/index.css
  recipes/theme-ui/index.ts
  recipes/theme-ui/package.json
  recipes/theme-ui/templates/config/blitz.config.js
  recipes/theme-ui/templates/layouts/MdxLayout.tsx
  recipes/theme-ui/templates/theme/theme/components.tsx
  recipes/theme-ui/templates/theme/theme/index.ts
Labels: status/done

#1564 Change passport adapter to accept an array of objects with authenticate options for each strategy
  examples/auth/app/api/auth/[...auth].ts
  packages/core/src/passport-adapter.ts
  packages/core/src/types.ts
Labels: status/in-review

#1478 Add `blitz routes` command to see all routes
  .gitignore
  packages/cli/src/commands/routes.ts
  packages/cli/test/commands/routes.test.ts
  packages/display/package.json
  packages/display/src/index.ts
  packages/file-pipeline/src/display.ts
  packages/file-pipeline/src/helpers/route-cache.ts
  packages/file-pipeline/src/index.ts
  packages/file-pipeline/src/pipeline.ts
  packages/file-pipeline/src/types.ts
  packages/server/src/config.ts
  packages/server/src/index.ts
  packages/server/src/routes.ts
  packages/server/src/stages/index.ts
  packages/server/src/stages/pages/index.ts
  packages/server/src/stages/routes/index.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/stages/stage-test-utils.ts
  packages/server/test/routes.test.ts
  yarn.lock
Labels: status/in-review

#1540 Remove error stack from console output on testing
  packages/core/src/middleware.test.ts
  packages/core/src/middleware.ts
Labels: status/in-review

#1583 Fix and improve Theme UI recipe
  README.md
  recipes/theme-ui/index.ts
  recipes/theme-ui/templates/layouts/MdxLayout.tsx
  recipes/theme-ui/templates/pages/demo.mdx
  recipes/theme-ui/templates/theme/theme/index.ts
Labels: status/in-review

#1595 (newapp) Change prisma version to be pinned to a minor version
  packages/generator/templates/app/package.json
Labels: status/in-review

#1594 Fix bug where "db" in a path name will break client side imports (patch)
  packages/server/src/with-blitz.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1597 Minor typo fix in chakra recipe explanation
  recipes/chakra/index.ts
Labels: status/in-review

#1607 Removed `unstable_` prefix from session middleware
  examples/auth/blitz.config.js
  examples/fauna/blitz.config.js
  packages/core/src/supertokens.ts
  packages/generator/templates/app/blitz.config.js
  packages/server/src/supertokens.test.ts
  packages/server/src/supertokens.ts
  recipes/theme-ui/templates/config/blitz.config.js
Labels: status/in-review

#1613 Add missing exports for `LinkProps`, `ImageProps`, and `ErrorProps`
  packages/core/src/index.ts
Labels: status/in-review

#1616 Fix bug where cancelling `blitz install` still outputs success message
  packages/installer/src/recipe-executor.tsx
Labels: status/in-review

#1618 Fix: allow numbers and underscore in names for `blitz generate model`
  packages/generator/src/prisma/field.ts
  packages/generator/test/prisma/field.test.ts
Labels: status/in-review

#1635 Skip flaky windows packages test
  packages/file-pipeline/package.json
  packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts
  packages/generator/package.json
  packages/installer/package.json
  packages/repl/package.json
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#1637 Added Reo as L1 Maintainer to the README
  README.md
Labels: status/in-review

#1640 Timeout example testing after 20mins
  .github/workflows/main.yml
Labels: status/in-review

#1643 Change all agnosticSource tests to not run on windows
  .github/workflows/main.yml
  packages/core/src/middleware.test.ts
  packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts
  packages/installer/test/utils/paths.test.ts
Labels: status/in-review

#1639 Fix CI windows example test and other CI maintenance
  .github/workflows/compressed.yml
  .github/workflows/main.yml
  examples/auth/package.json
  examples/store/assert-tree-shaking-works.js
  examples/store/package.json
  yarn.lock
Labels: status/in-review

#1633 Remove unused packages from `@blitzjs/installer` (patch)
  packages/installer/package.json
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1627 Remove internal `hasha` dependency (patch)
  packages/server/package.json
  packages/server/src/supertokens.ts
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1631 Remove unused packages from `@blitzjs/file-pipeline` (patch)
  packages/file-pipeline/package.json
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1632 Remove unsued internal dep `node-fetch` (patch)
  packages/generator/package.json
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1645 Fix broken css module imports (patch)
  examples/store/app/admin/pages/admin/index.module.scss
  examples/store/app/admin/pages/admin/index.tsx
  examples/store/types.d.ts
  packages/server/src/stages/rewrite-imports/index.ts
  packages/server/src/stages/rewrite-imports/rewrite-imports.test.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1642 Simplify internal dependencies for `fetch` (patch)
  package.json
  packages/core/src/invoke.test.ts
  packages/core/src/middleware.test.ts
  packages/server/src/supertokens.test.ts
  packages/server/test/rpc.test.ts
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1630 Remove unused packages from `core` (patch)
  packages/core/package.json
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1648 Fix `blitz db` commands showing incorrect error (patch)
  packages/cli/src/commands/db.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1623 Remove implicit auto-build with `blitz start --production`. `blitz build` now a pre-requisite (major)
  examples/auth/package.json
  examples/plain-js/yarn.lock
  examples/store/package.json
  packages/server/package.json
  packages/server/src/build-hash.ts
  packages/server/src/build.ts
  packages/server/src/folder-hash.d.ts
  packages/server/src/prod.ts
  packages/server/test/build.test.ts
  packages/server/test/prod.test.ts
  packages/server/test/vercel-now.test.ts
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1649 Fix bug preventing imports from files/libraries ending in "pages" or "api" (patch)
  examples/store/app/products/api.ts
  examples/store/app/products/pages/products/index.tsx
  examples/store/cypress/integration/products.test.ts
  packages/server/src/stages/rewrite-imports/index.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1628 Remove `pretty-ms` dependency (move code into core) (patch)
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/invoke.ts
  packages/core/src/utils/pretty-ms.test.ts
  packages/core/src/utils/pretty-ms.ts
  packages/server/package.json
  packages/server/src/rpc.ts
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1634 Remove unused packages from `@blitzjs/server` (patch)
  packages/server/package.json
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1653 Improve error message from `useQuery` for case of incorrect resolver location (patch)
  packages/core/src/utils/react-query-utils.ts
  packages/core/test/__snapshots__/use-mutation.test.tsx.snap
  packages/core/test/__snapshots__/use-query.test.tsx.snap
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1654 Fix a false duplicate error with `.coverage` directory in your project (patch)
  packages/server/src/config.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1658 (newapp) Change Final Form `<LabeledTextField/>` to properly parse numbers
  packages/generator/templates/app/_forms/finalform/LabeledTextField.tsx
Labels: status/in-review

#1657 Upgrade all dependencies (patch)
  .eslintrc.js
  .gitignore
  examples/auth/package.json
  examples/fauna/package.json
  examples/no-prisma/package.json
  examples/plain-js/package.json
  examples/store/package.json
  package.json
  packages/blitz/package.json
  packages/cli/package.json
  packages/cli/test/commands/new.test.ts
  packages/core/package.json
  packages/display/package.json
  packages/display/src/index.ts
  packages/file-pipeline/package.json
  packages/file-pipeline/src/helpers/work-optimizer/index.ts
  packages/file-pipeline/src/test-utils.ts
  packages/generator/package.json
  packages/generator/src/generator.ts
  packages/generator/src/generators/app-generator.ts
  packages/installer/package.json
  packages/installer/src/recipe-executor.tsx
  packages/repl/package.json
  packages/server/package.json
  packages/server/src/next-utils.ts
  packages/server/src/rpc.ts
  packages/server/src/stages/rewrite-imports/index.ts
  packages/server/src/stages/stage-test-utils.ts
  packages/server/test/prod.test.ts
  recipes/base-web/package.json
  recipes/chakra/index.ts
  recipes/chakra/package.json
  recipes/emotion/package.json
  recipes/material-ui/package.json
  recipes/reflexjs/package.json
  recipes/tailwind/package.json
  recipes/theme-ui/package.json
  yarn.lock
Labels: status/in-review
