Repository blitz-js/blitz, pull requests merged in 2020-09, with the labels that each got.

#979 Upgrade environment variable support to match Next.js (use dotenv-flow)
  .gitignore
  package.json
  packages/cli/package.json
  packages/cli/src/commands/new.ts
  packages/cli/src/index.ts
  packages/generator/.gitignore
  packages/generator/templates/app/.env
  packages/generator/templates/app/.env.local
  packages/generator/templates/app/.env.test.local
  packages/generator/templates/app/README.md
  packages/generator/templates/app/gitignore
  yarn.lock
Labels: status/in-review

#981 Revert default react version to 0.0.0-experimental-7f28234f8 because of error boundary bug
  examples/auth/package.json
  examples/no-prisma/package.json
  examples/plain-js/package.json
  examples/store/package.json
  examples/tailwind/package.json
  packages/generator/templates/app/package.json
  packages/installer/package.json
  yarn.lock
Labels: status/in-review

#982 Fix Undefined function `deleteCookie` error after session expires
  packages/core/src/supertokens.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#985 Improve the `useCurrentUser()` hook in the new app template
  examples/auth/app/hooks/useCurrentUser.ts
  examples/auth/blitz.config.js
  packages/generator/templates/app/app/hooks/useCurrentUser.ts
Labels: status/in-review

#986 Fix `blitz db reset`
  packages/cli/package.json
  packages/cli/src/commands/db.ts
  yarn.lock
Labels: status/in-review

#990 Moves auth and recipes to features section
  README.md
Labels: status/in-review

#996 Fix CI by removing browser setting for cypress
  examples/auth/package.json
Labels: status/in-review

#995 Fix some cache key issues with `useQuery`
  packages/core/src/supertokens.ts
  packages/core/src/use-infinite-query.ts
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
  packages/core/src/utils/query-cache.ts
Labels: status/in-review

#991 Upgrade Next.js from 9.5.2 to 9.5.3
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#998 Adds no-use-before-define lint rule
  .eslintrc.js
  packages/core/src/supertokens.ts
  packages/core/test/test-utils.tsx
  packages/file-pipeline/src/helpers/writer/index.ts
  packages/file-pipeline/src/transform-files/index.ts
  packages/repl/src/repl.ts
  packages/server/src/rpc.ts
  packages/server/src/stages/relative/index.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/supertokens.ts
  packages/server/test/rpc.test.ts
Labels: status/in-review

#1021 Minor improvements to default `auth-utils.ts` file
  examples/auth/app/auth/auth-utils.ts
  packages/generator/templates/app/app/auth/auth-utils.ts
Labels: status/in-review

#1019 Fix react warnings from Formik in new apps
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/auth/components/SignupForm.tsx
  packages/generator/templates/app/app/auth/pages/signup.tsx
Labels: status/in-review

#1023 Fix Heroku issue where `blitz start --production` always rebuilds even after running `blitz build`
  packages/server/src/build-hash.ts
Labels: status/in-review

#1029 Fix heroku rebuilding on start
  packages/server/src/build-hash.ts
  packages/server/src/config.ts
Labels: status/in-review

#1030 Fix `ctx.session.authorize()` throwing AuthorizationError instead of AuthenticationError if user logged out. (#1030)
  packages/server/src/supertokens.ts
Labels: status/in-review

#1038 Fix UnhandledPromiseRejectionWarning from useQuery during static pre-rendering
  packages/core/src/use-infinite-query.ts
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
Labels: status/in-review

#1012 Enable passing extra prisma args to `blitz db migrate`
  packages/cli/src/commands/db.ts
  packages/cli/test/commands/db.test.ts
Labels: status/in-review

#1024 Add ability to set custom `authenticateOptions` for the Passport.js adapter
  examples/auth/app/api/auth/[...auth].ts
  examples/auth/package.json
  packages/core/src/passport-adapter.ts
  yarn.lock
Labels: status/in-review

#1034 Fix: export `AppProps` as a generic type
  packages/core/src/index.ts
Labels: status/in-review

#1036 Update dependencies in new app template
  packages/generator/templates/app/package.json
Labels: status/in-review

#1033 Add `secureProxy` option the the Passport.js adapter
  packages/core/src/middleware.ts
  packages/core/src/passport-adapter.ts
  packages/core/src/secure-proxy-middleware.test.ts
  packages/core/src/secure-proxy-middleware.ts
Labels: status/in-review

#1045 Fix bug where test files would cause `blitz build` to fail
  packages/server/src/config.ts
Labels: status/in-review

#1014 refactor(server): Added isTypescript explicit flag, config refactored
  packages/cli/src/commands/start.ts
  packages/file-pipeline/src/transform-files/index.ts
  packages/file-pipeline/src/types.ts
  packages/server/src/build.ts
  packages/server/src/config.ts
  packages/server/src/dev.ts
  packages/server/src/stages/index.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/stages/stage-test-utils.ts
Labels: status/in-review

#1050 Add link to signup page to login form for new apps
  examples/auth/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  yarn.lock
Labels: status/in-review

#1051 Tiny tweak to Layout component in new apps
  packages/generator/templates/app/app/layouts/Layout.tsx
Labels: status/in-review

#1054 Fix bug in default `_app.tsx` where Links inside ErrorBoundary don't work
  examples/auth/app/pages/_app.tsx
  examples/auth/app/users/queries/getUsers.ts
  packages/generator/templates/app/app/pages/_app.tsx
Labels: status/in-review

#1059 Fix type error for useQuery/usePaginatedQuery options object
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
Labels: status/in-review

#1057 Significantly improve CLI performance: reduce execute time from 1700ms -> 900ms
  .gitignore
  packages/cli/package.json
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/console.ts
  packages/cli/src/commands/db.ts
  packages/cli/src/commands/generate.ts
  packages/cli/src/commands/install.ts
  packages/cli/src/commands/new.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/test.ts
  packages/cli/src/index.ts
  packages/cli/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: status/in-review

#1063 Add `--inspect` flag to enable Node.js inspector
  packages/cli/src/commands/start.ts
  packages/server/src/config.ts
  packages/server/src/next-utils.ts
Labels: status/in-review

#1064 Fix an incorrect error message in `blitz start`
  packages/server/src/next-utils.ts
Labels: status/in-review

#1083 Fix `blitz generate query` does not preserve plurality
  packages/cli/src/commands/generate.ts
  packages/generator/src/generators/query-generator.ts
  packages/generator/templates/query/__modelName__.ts
  packages/generator/templates/query/__rawInput__.ts
Labels: status/in-review

#1091 Change the new app schema provider to be just `sqlite` instead of an array
  packages/generator/templates/app/.env.local
  packages/generator/templates/app/.env.test.local
  packages/generator/templates/app/db/schema.prisma
Labels: status/in-review

#1095 Improve rendering of errors in generated Final Form <LabeledTextField>
  packages/generator/templates/app/_forms/finalform/LabeledTextField.tsx
Labels: status/in-review

#1108 Improve Recipe for Render.com
  recipes/render/templates/render.yaml
Labels: status/in-review

#1104 Tweaks to new app template pkg scripts: add tsc to pre-commit and lint to pre-push
  packages/generator/templates/app/package.json
Labels: status/in-review

#1089 Fix `blitz generate pages` to use kebab-case for all url paths
  packages/generator/src/generators/page-generator.ts
  packages/generator/src/utils/kebab-case.ts
  packages/generator/test/utils/kebab-case.test.ts
Labels: status/in-review

#1102 Add `test`, `tests`, `spec`, `specs` to build hash ignore list
  packages/server/src/build-hash.ts
Labels: status/in-review

#1111 Fix inability to have a `/test` page
  packages/server/src/stages/pages/index.ts
  packages/server/src/stages/pages/pages-path-transformer.test.ts
Labels: status/in-review

#1112 Add dotenv-flow to jest config for new apps
  packages/generator/templates/app/test/setup.ts
Labels: status/in-review

#1119 🎉 Add Satoshi Nitawaki as L1 Maintainer
  .all-contributorsrc
  README.md
Labels: status/in-review

#1107 Add --force flag for `blitz db reset` command
  packages/cli/src/commands/db.ts
  packages/cli/test/commands/db.test.ts
Labels: status/in-review

#1087 Fix cli cache file to be in temp directory instead of project directory
  packages/cli/src/index.ts
Labels: status/in-review

#1092 Enable automatic network request cancelation for queries/mutations
  packages/core/src/rpc.ts
Labels: status/in-review

#1116 Fix `blitz new` spewing out all the database migration logs
  packages/cli/src/commands/db.ts
Labels: scope/cli, status/in-review

#1117 Fix slack channel name in MAINTAINERS.md
  MAINTAINERS.md
Labels: kind/docs, priority/low, status/in-review

#1121 Remove prisma client generation from blitz in favor of new package.json schema config (Requires Prisma 2.7.0+ & new field in pkg.json))
  packages/cli/src/commands/build.ts
  packages/cli/src/commands/console.ts
  packages/cli/src/commands/db.ts
  packages/cli/src/commands/start.ts
  packages/cli/test/commands/console.test.ts
  packages/generator/templates/app/package.json
Labels: status/in-review

#1124 Fix ES5 compatibility
  package.json
  packages/core/.eslintrc.js
  packages/core/package.json
  packages/core/src/middleware.ts
  packages/core/src/passport-adapter.ts
  packages/core/src/rpc.ts
  packages/core/src/use-params.ts
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#1118 Update Taiwind recipe to opt in to future Tailwind CSS changes
  recipes/tailwind/templates/config/tailwind.config.js
Labels: status/in-review

#1135 (newapp) Change signup & login to lowerCase emails before saving and verifying
  packages/generator/templates/app/app/auth/auth-utils.ts
  packages/generator/templates/app/app/auth/mutations/signup.ts
Labels: status/in-review

#1136 Improve error message for missing SESSION_SECRET_KEY
  packages/server/src/supertokens.ts
Labels: status/in-review

#1129 add lint rule to prevent Object.fromEntries in core package
  package.json
  packages/core/.eslintrc.js
  yarn.lock
Labels: status/in-review

#1122 Fix `blitz autocomplete` adding alpha warning message to the shell config
  packages/blitz/src/bin/cli.ts
Labels: status/in-review

#1132 Add a timeout to the "retrieving freshest dependencies" step for `blitz new`
  packages/generator/src/utils/npm-fetch.ts
Labels: status/in-review

#1144 (newapp) Improve Form typing: remove need to pass schema type
  examples/auth/app/auth/components/LoginForm.tsx
  examples/auth/app/auth/pages/signup.tsx
  examples/auth/app/components/Form.tsx
  packages/generator/templates/app/_forms/finalform/Form.tsx
  packages/generator/templates/app/_forms/formik/Form.tsx
  packages/generator/templates/app/_forms/hookform/Form.tsx
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/auth/components/SignupForm.tsx
Labels: status/in-review

#1137 Speed up `blitz start` by 40% by adding incremental dev cache
  package.json
  packages/cli/src/commands/start.ts
  packages/file-pipeline/src/helpers/enrich-files.ts
  packages/file-pipeline/src/helpers/work-optimizer/README.md
  packages/file-pipeline/src/helpers/work-optimizer/index.ts
  packages/file-pipeline/src/helpers/work-optimizer/work-optimizer.test.ts
  packages/file-pipeline/src/helpers/writer/index.ts
  packages/file-pipeline/src/pipeline.ts
  packages/file-pipeline/src/test-utils.ts
  packages/file-pipeline/src/transform-files/highwatermark.test.ts
  packages/file-pipeline/src/transform-files/index.ts
  packages/file-pipeline/src/transform-files/transform-files.test.ts
  packages/file-pipeline/src/types.ts
  packages/file-pipeline/src/utils.ts
  packages/server/src/build.ts
  packages/server/src/config.ts
  packages/server/src/dev.ts
  packages/server/src/stages/config/index.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/stages/stage-test-utils.ts
  yarn.lock
Labels: status/in-review

#678 Add `blitz db seed` for seeding data in your database
  examples/store/db/seeds.ts
  packages/cli/src/commands/db.ts
  packages/cli/src/commands/seed.ts
  packages/cli/test/__fixtures__/db/index.ts
  packages/cli/test/__fixtures__/db/seeds.ts
  packages/cli/test/commands/seed.test.ts
  packages/generator/templates/app/db/seeds.ts
Labels: status/in-review

#1142 Fix `blitz console` not closing on first Ctrl+D
  packages/repl/src/repl.ts
Labels: status/in-review

#945 Upgrade react-query to 2.23.0
  examples/store/app/admin/pages/admin/products/[id].tsx
  examples/store/cypress/integration/admin/products/edit.test.ts
  packages/core/package.json
  packages/core/src/use-infinite-query.ts
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/query-cache.ts
  yarn.lock
Labels: status/in-review

#1147 Fix ES5 compatibility: upgrade superjson to 1.2.2
  examples/store/package.json
  packages/core/package.json
  packages/server/package.json
  yarn.lock
Labels: status/in-review

#1156 Fix: pass undefined through the RPC layer
  packages/core/src/rpc.ts
Labels: status/in-review

#1140 (newapp) Add "restart server" to instruction to index page
  packages/generator/templates/app/app/pages/index.tsx
Labels: status/in-review

#1172 Big refactor of internal types for react-query, RPC, and resolvers
  examples/auth/app/auth/mutations/logout.ts
  examples/auth/app/pages/ssr.tsx
  examples/auth/app/users/components/UserForm.tsx
  examples/auth/app/users/mutations/createUser.ts
  examples/auth/app/users/mutations/deleteUser.ts
  examples/auth/app/users/mutations/updateUser.ts
  examples/auth/app/users/pages/users/[userId].tsx
  examples/auth/app/users/pages/users/[userId]/edit.tsx
  examples/auth/app/users/pages/users/index.tsx
  examples/auth/app/users/pages/users/new.tsx
  examples/auth/app/users/queries/getUser.ts
  examples/auth/cypress/plugins/index.ts
  examples/store/app/admin/pages/admin/products/[id].tsx
  examples/store/cypress/integration/admin/products/edit.test.ts
  packages/core/src/index.ts
  packages/core/src/middleware.ts
  packages/core/src/rpc.ts
  packages/core/src/ssr-query.test.ts
  packages/core/src/ssr-query.ts
  packages/core/src/types.ts
  packages/core/src/use-infinite-query.ts
  packages/core/src/use-paginated-query.ts
  packages/core/src/use-query-hooks.ts
  packages/core/src/use-query.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/query-cache.ts
  packages/core/src/utils/react-query-utils.ts
  packages/core/test/react-query-utils.test.ts
  packages/core/test/rpc.test.ts
  packages/core/test/use-query.test.tsx
  packages/generator/templates/app/app/auth/mutations/logout.ts
  packages/server/src/rpc.ts
  packages/server/src/stages/rpc/index.ts
  packages/server/src/supertokens.test.ts
  packages/server/test/rpc.test.ts
Labels: status/in-review

#1160 🔥 Add `useMutation()` and strong typing for `ctx` and `ctx.session`
  examples/auth/app/auth/components/LoginForm.tsx
  examples/auth/app/auth/mutations/login.ts
  examples/auth/app/auth/mutations/logout.ts
  examples/auth/app/auth/mutations/signup.ts
  examples/auth/app/auth/pages/signup.tsx
  examples/auth/app/layouts/Layout.tsx
  examples/auth/app/users/mutations/trackView.ts
  examples/auth/app/users/queries/getCurrentUser.ts
  examples/auth/app/users/queries/getUser.ts
  examples/auth/app/users/queries/getUsers.ts
  examples/auth/types.ts
  packages/core/src/index.ts
  packages/core/src/middleware.ts
  packages/core/src/use-mutation.ts
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/auth/components/SignupForm.tsx
  packages/generator/templates/app/app/auth/mutations/login.ts
  packages/generator/templates/app/app/auth/mutations/logout.ts
  packages/generator/templates/app/app/auth/mutations/signup.ts
  packages/generator/templates/app/app/users/queries/getCurrentUser.ts
  packages/generator/templates/app/types.ts
  packages/generator/templates/mutation/create__ModelName__.ts
  packages/generator/templates/mutation/delete__ModelName__.ts
  packages/generator/templates/mutation/update__ModelName__.ts
  packages/generator/templates/queries/get__ModelName__.ts
  packages/generator/templates/queries/get__ModelNames__.ts
  packages/generator/templates/query/__rawInput__.ts
Labels: status/in-review

#1148 Add .node-version
  .node-version
Labels: status/in-review

#1161 Fix bug in dev where files were not being removed correctly when deleted
  packages/file-pipeline/src/helpers/unlink/index.ts
  packages/file-pipeline/src/helpers/unlink/unlink.test.ts
Labels: status/in-review

#1176 Fix useQuery's mutate and router.push in same frame will cause error
  packages/core/src/types.ts
  packages/core/src/utils/react-query-utils.ts
  packages/core/test/react-query-utils.test.ts
  packages/generator/templates/page/__modelIdParam__/edit.tsx
Labels: status/in-review

#1177 Disable automatic query request cancellation
  packages/core/src/rpc.ts
Labels: status/in-review

#1179 Use npm for husky pre-push hook instead of yarn
  packages/generator/templates/app/package.json
Labels: status/in-review

#1181 Fix types for useQuery that were broken with useMutation addition
  examples/auth/app/pages/index.tsx
  examples/auth/app/pages/ssr.tsx
  examples/store/app/admin/pages/admin/products/index.tsx
  examples/store/app/products/components/ProductForm.tsx
  examples/store/app/products/mutations/updateProduct.ts
  examples/store/app/products/pages/products/[handle].tsx
  examples/store/app/products/queries/getProduct.ts
  packages/core/src/types.ts
  packages/core/src/use-query-hooks.ts
Labels: status/in-review

#1157 Reduce re-renders by memoizing useParams and useRouterQuery
  packages/core/src/use-params.ts
  packages/core/src/use-router-query.ts
Labels: status/in-review

#1165 (newapp) Fix tests not working out of the box
  packages/generator/templates/app/jest.config.js
Labels: status/in-review

#1184 Adds tests for core parsePublicDataToken
  packages/core/src/supertokens.test.ts
  packages/core/src/supertokens.ts
Labels: status/in-review

#1194 Fix a resolver type build error (on canary)
  packages/core/src/types.ts
Labels: status/in-review

#1195 Minor updates to pages/queries/mutations templates (add useMutation and use db.findFirst)
  packages/generator/templates/mutation/create__ModelName__.ts
  packages/generator/templates/mutation/delete__ModelName__.ts
  packages/generator/templates/mutation/update__ModelName__.ts
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
  packages/generator/templates/queries/get__ModelName__.ts
  packages/generator/templates/queries/get__ModelNames__.ts
Labels: status/in-review

#1200 Fix bug with creating new session after revoking current one
  packages/server/src/supertokens.ts
Labels: status/in-review
