Repository blitz-js/blitz, pull requests merged in 2021-06, with the labels that each got.

#2426 add missing debug dependency to blitz package (patch)
  packages/blitz/package.json
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#2427 Fix so `blitz new` always generates valid cookiePrefix
  packages/generator/src/generators/app-generator.ts
  packages/generator/templates/app/blitz.config.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#2439 add couple missing dependencies to @blitzjs/cli package (patch)
  packages/blitz/package.json
  packages/cli/package.json
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#2435 Add helpful error when trying `blitz export` with blitz auth (patch)
  .gitignore
  nextjs/packages/next/build/index.ts
  nextjs/packages/next/build/utils.ts
  nextjs/packages/next/export/index.ts
  nextjs/test/integration/export-intent/test/index.test.js
  packages/cli/src/commands/export.ts
  packages/core/src/server/auth/sessions.ts
  test/integration/auth/pages/_app.tsx
  test/integration/auth/test/index.test.ts
  test/integration/export-image-default/babel.config.js
  test/integration/export-image-default/blitz.config.js
  test/integration/export-image-default/pages/_app.js
  test/integration/export-image-default/pages/index.js
  test/integration/export-image-default/test/index.test.js
  test/integration/misc/test/index.test.ts
  test/lib/blitz-test-utils.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#2445 Fix Prisma @@map in Enums break the model generator
  packages/generator/package.json
  packages/installer/package.json
  yarn.lock
Labels: status/in-review

#2451 Remove unneeded `cd` message during `blitz install` in some cases
  packages/cli/src/commands/new.ts
Labels: status/in-review

#2447 Add ability to disable custom server hot reloading
  packages/config/src/index.ts
  packages/server/src/dev.ts
Labels: status/in-review

#2443 Fix CSRF 401 errors for HEAD requests (patch)
  packages/core/src/server/auth/sessions.test.ts
  packages/core/src/server/auth/sessions.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#2424 Fix Routes manifest for pages with parent & child relationships (patch)
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
Labels: status/in-review

#2462 (newapp) Update Prisma and React dependencies
  examples/auth/package.json
  examples/custom-server/package.json
  examples/plain-js/package.json
  examples/static/package.json
  examples/store/package.json
  packages/cli/package.json
  packages/generator/templates/app/package.json
  yarn.lock
Labels: status/in-review

#2463 Fix auth & middleware not working on Vercel (No longer need the `path.resolve` workaround) (patch)
  .eslintignore
  .github/workflows/main.yml
  examples/store/app/admin/api/users.ts
  examples/store/app/admin/pages/admin/products/index.tsx
  packages/babel-preset/src/fix-node-file-trace/fix-node-file-trace.test.ts
  packages/babel-preset/src/fix-node-file-trace/index.ts
  packages/babel-preset/src/fix-node-file-trace/tests/pages/api/api-route/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/api/api-route/output.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/class component/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/class component/output.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSP arrow function with implicit return/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSP arrow function with implicit return/output.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSP arrow function/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSP arrow function/output.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSP function declaration/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSP function declaration/output.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSSP function declaration/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/gSSP function declaration/output.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/separate export declaration/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/separate export declaration/output.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/transforms a valid example/code.js
  packages/babel-preset/src/fix-node-file-trace/tests/pages/transforms a valid example/output.js
  packages/babel-preset/src/index.ts
  packages/core/src/server/index.ts
  packages/server/src/stages/rpc/index.ts
  patches/@preconstruct+cli+2.0.7.patch
  test/integration/export-image-default/pages/index.js
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#2408 Fix to not build custom server during `blitz start`
  packages/server/src/build.ts
  packages/server/src/next-utils.ts
  packages/server/test/build.test.ts
  packages/server/test/vercel-now.test.ts
Labels: status/in-review

#2453 Fix webpack 5 support (Webpack 5 now used by default) (patch)
  .github/workflows/main.yml
  .prettierignore
  examples/store/app/products/pages/products/index.tsx
  examples/store/app/products/queries/getProducts.ts
  nextjs/.prettierignore
  nextjs/packages/next/build/webpack-config.ts
  nextjs/packages/next/next-server/server/config-shared.ts
  nextjs/packages/next/package.json
  nextjs/packages/next/server/lib/utils.ts
  nextjs/test/integration/build-output/test/index.test.js
  nextjs/test/integration/size-limit/test/index.test.js
  packages/config/index-browser.js
  packages/config/package.json
  packages/config/src/index.ts
  packages/core/package.json
  packages/core/src/server/auth/sessions.ts
  packages/core/src/server/index.ts
  packages/core/src/with-blitz.test.ts
  packages/core/src/with-blitz.ts
  packages/core/with-blitz/package.json
  packages/server/src/stages/config/index.ts
  patches/@preconstruct+cli+2.0.7.patch
Labels: status/in-review

#2464 Fix one part of pnp issues (patch)
  packages/blitz/scripts/postinstall.js
Labels: status/in-review

#2475 (newapp) move dev dependencies to devDependencies in package.json (better for Docker)
  packages/generator/templates/app/package.json
Labels: status/in-review

#2471 fix `BlitzConfig` type to allow extra fields (patch)
  packages/config/src/index.ts
Labels: 0 - <(^_^)> - merge it! ✌️

#2476 fix pages to never render if `Page.authenticate=true` and logged out (patch)
  packages/core/src/auth/auth-client.ts
  test/integration/auth/pages/page-dot-authenticate-logout.tsx
  test/integration/auth/pages/page-dot-authenticate.tsx
  test/integration/auth/test/index.test.ts
Labels: status/in-review

#2441 Add `validateZodSchema()` API for better form errors
  examples/auth/app/core/components/Form.tsx
  examples/custom-server/app/components/Form.tsx
  examples/fauna/app/components/Form.tsx
  packages/core/src/index.ts
  packages/core/src/utils/index.test.ts
  packages/core/src/utils/index.ts
  packages/generator/templates/app/_forms/finalform/Form.tsx
  packages/generator/templates/app/_forms/formik/Form.tsx
Labels: status/in-review

#2479 fix broken vercel deployments (patch)
  packages/core/src/server/auth/sessions.ts
  packages/core/src/server/index.ts
  test/integration/auth-serverless/app/mutations/login.ts
  test/integration/auth-serverless/app/mutations/logout.ts
  test/integration/auth-serverless/app/queries/getAuthenticatedBasic.ts
  test/integration/auth-serverless/app/queries/getNoauthBasic.ts
  test/integration/auth-serverless/babel.config.js
  test/integration/auth-serverless/blitz.config.ts
  test/integration/auth-serverless/db.ts
  test/integration/auth-serverless/pages/_app.tsx
  test/integration/auth-serverless/pages/_document.tsx
  test/integration/auth-serverless/pages/authenticated-query.tsx
  test/integration/auth-serverless/pages/login.tsx
  test/integration/auth-serverless/pages/noauth-query.tsx
  test/integration/auth-serverless/test/index.test.ts
  test/integration/auth-serverless/tsconfig.json
  test/integration/auth-serverless/types.ts
Labels: status/in-review

#2480 Add <ErrorBoundary> component (major)
  examples/auth/app/pages/_app.tsx
  examples/auth/package.json
  examples/custom-server/app/pages/_app.tsx
  examples/custom-server/package.json
  examples/fauna/app/pages/_app.tsx
  examples/fauna/package.json
  examples/static/app/pages/_app.tsx
  examples/static/package.json
  examples/store/app/pages/_app.tsx
  examples/store/package.json
  package.json
  packages/core/src/error-boundary.hook.test.tsx
  packages/core/src/error-boundary.test.tsx
  packages/core/src/error-boundary.tsx
  packages/core/src/index.ts
  packages/core/src/router/index.tsx
  packages/generator/templates/app/app/pages/_app.tsx
  packages/generator/templates/app/package.json
  test/integration/auth-serverless/pages/_app.tsx
  test/integration/auth/pages/_app.tsx
  test/integration/misc/pages/body-parser.tsx
  yarn.lock
Labels: status/in-review

#2473 Add `setPublicDataForUser()` — useful for updating the role of another user
  packages/babel-preset/src/rewrite-imports.ts
  packages/core/src/server/auth/sessions.ts
  packages/core/src/server/index.ts
  test/integration/auth/app/mutations/changeRole.ts
  test/integration/auth/app/queries/getPublicDataForUser.ts
  test/integration/auth/pages/set-public-data.tsx
  test/integration/auth/test/index.test.ts
Labels: status/in-review

#2483 fix `Page.authenticate = {redirect: '/login'}` not working correctly on logout AND add RedirectError (patch)
  packages/core/src/auth/auth-client.ts
  packages/core/src/blitz-app-root.tsx
  packages/core/src/error-boundary.tsx
  packages/core/src/errors.ts
  packages/core/src/rpc-client.ts
  packages/core/src/utils/index.ts
  test/integration/auth/pages/login.tsx
  test/integration/auth/pages/page-dot-authenticate-redirect.tsx
  test/integration/auth/test/index.test.ts
Labels: status/in-review

#2488 fix CI by upgrading browserslist
  nextjs/packages/next/compiled/postcss-preset-env/index.js
  package.json
  yarn.lock
Labels: status/in-review

#2487 Fix edit page generated by `blitz generate` to not have buggy behavior
  examples/auth/app/pages/projects/[projectId]/edit.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
Labels: status/in-review

#2474 Fix bug with <Image> and SSR for configured domains
  nextjs/packages/next/client/image.tsx
  packages/babel-preset/src/rewrite-imports.test.ts
  packages/babel-preset/src/rewrite-imports.ts
  packages/blitz/src/index.ts
  packages/core/image/package.json
  packages/core/package.json
  packages/core/src/image.ts
  test/integration/images/app/queries/getBasic.ts
  test/integration/images/app/queries/getError.ts
  test/integration/images/babel.config.js
  test/integration/images/blitz.config.js
  test/integration/images/pages/_app.tsx
  test/integration/images/pages/_document.tsx
  test/integration/images/pages/image-ssr.tsx
  test/integration/images/test/index.test.ts
  test/integration/images/tsconfig.json
Labels: status/in-review

#2438 Change all user facing references of next.js to blitz.js
  .github/workflows/main.yml
  nextjs/packages/next/bin/next.ts
  nextjs/packages/next/build/index.ts
  nextjs/packages/next/build/utils.ts
  nextjs/packages/next/build/webpack-config.ts
  nextjs/packages/next/build/webpack/config/blocks/css/plugins.ts
  nextjs/packages/next/cli/next-build.ts
  nextjs/packages/next/cli/next-dev.ts
  nextjs/packages/next/cli/next-export.ts
  nextjs/packages/next/cli/next-start.ts
  nextjs/packages/next/cli/next-telemetry.ts
  nextjs/packages/next/client/dev/error-overlay/format-webpack-messages.js
  nextjs/packages/next/client/image.tsx
  nextjs/packages/next/client/link.tsx
  nextjs/packages/next/export/index.ts
  nextjs/packages/next/next-server/server/config-utils.ts
  nextjs/packages/next/next-server/server/config.ts
  nextjs/packages/next/next-server/server/render.tsx
  nextjs/packages/next/server/next-dev-server.ts
  nextjs/packages/next/telemetry/storage.ts
  nextjs/test/acceptance/ReactRefreshLogBox.dev.test.js
  nextjs/test/integration/auto-export-error-bail/test/index.test.js
  nextjs/test/integration/cli/test/index.test.js
  nextjs/test/integration/config-empty/test/index.test.js
  nextjs/test/integration/dynamic-routing/test/index.test.js
  nextjs/test/integration/errors-on-output-to-public/test/index.test.js
  nextjs/test/integration/errors-on-output-to-static/test/index.test.js
  nextjs/test/integration/export-image-default/test/index.test.js
  nextjs/test/integration/image-component/base-path/test/index.test.js
  nextjs/test/integration/image-component/default/test/index.test.js
  nextjs/test/integration/page-extensions/test/index.test.js
  nextjs/test/integration/relay-analytics-disabled/test/index.test.js
  nextjs/test/integration/relay-analytics/test/index.test.js
  nextjs/test/integration/scss/test/index.test.js
  nextjs/test/integration/undefined-webpack-config/test/index.test.js
  nextjs/test/isolated/config.unit.test.js
  nextjs/test/unit/handles-incorrect-react.unit.test.js
  package.json
  test/integration/export-image-default/test/index.test.js
Labels: status/in-review

#2494 add `formatZodError()` utility
  packages/core/src/index.ts
  packages/core/src/utils/index.test.ts
  packages/core/src/utils/index.ts
Labels: status/in-review

#2501 Fix `blitz generate` /new page does not use `Routes`
  examples/auth/app/pages/projects/new.tsx
  packages/generator/templates/page/new.tsx
Labels: status/in-review

#2511 fix `validateZodSchema()` to pass if schema undefined
  packages/core/src/utils/index.ts
Labels: status/in-review

#2504 Fix `blitz generate` to regenerate the Routes manifest
  packages/generator/package.json
  packages/generator/src/generators/page-generator.ts
Labels: status/in-review

#2510 Add support for custom messages and icons in recipes
  packages/installer/src/executors/executor.tsx
  packages/installer/src/executors/print-message-executor.tsx
  packages/installer/src/index.ts
  packages/installer/src/recipe-builder.ts
  packages/installer/src/recipe-executor.tsx
  packages/installer/src/recipe-renderer.tsx
  packages/installer/test/executors/__snapshots__/print-message-executor.test.tsx.snap
  packages/installer/test/executors/print-message-executor.test.tsx
Labels: status/in-review

#2498 Fix so that npm scripts don't run on `blitz install` recipes
  packages/cli/src/commands/install.ts
Labels: status/in-review

#2513 fix lint warning, unused `path` in generated api routes (patch)
  packages/server/src/stages/rpc/index.ts
Labels: status/in-review

#2514 Fix browser error when using `prisma.$use()`
  packages/core/src/prisma-utils.ts
Labels: status/in-review

#2517 Update userTrack logo (sponsor)
  assets/usertrack.png
Labels: status/in-review

#2512 Fix prefetched dehydrated state to support Dates, Maps, etc (patch)
  nextjs/run-tests.js
  nextjs/test/integration/config/test/index.test.js
  packages/babel-preset/src/index.ts
  packages/core/src/blitz-app-root.tsx
  test/integration/auth/pages/prefetching.tsx
  test/integration/auth/test/index.test.ts
  test/integration/queries/app/queries/getDate.ts
  test/integration/queries/pages/dehydrated-state.tsx
  test/integration/queries/test/index.test.ts
Labels: status/in-review

#2528 Fix `blitz db seed` to print stack traces for any errors
  packages/cli/src/commands/db.ts
Labels: status/in-review

#2522 Fix built in errors like RedirectError and AuthenticationError to not log as "uncaught" in browser console
  nextjs/packages/next/client/index.tsx
  nextjs/packages/next/package.json
  nextjs/packages/next/stdlib.d.ts
  nextjs/packages/next/stdlib.js
  nextjs/packages/next/stdlib/errors.ts
  nextjs/packages/next/stdlib/index.ts
  nextjs/packages/next/taskfile.js
  nextjs/test/integration/build-output/test/index.test.js
  nextjs/test/integration/fallback-modules/test/index.test.js
  nextjs/test/integration/size-limit/test/index.test.js
  packages/babel-preset/src/rewrite-imports.ts
  packages/blitz/src/index.ts
  packages/core/src/auth/auth-client.ts
  packages/core/src/blitz-app-root.tsx
  packages/core/src/error-boundary.tsx
  packages/core/src/index.ts
  packages/core/src/rpc-client.ts
  packages/core/src/server/auth/auth-utils.ts
  packages/core/src/server/auth/sessions.ts
  packages/core/src/server/server-utils.ts
Labels: status/in-review

#2502 Move multiple pages folders support plus pages+api sibling into nextjs core
  nextjs/packages/next/build/babel/loader/get-config.ts
  nextjs/packages/next/build/entries.ts
  nextjs/packages/next/build/index.ts
  nextjs/packages/next/build/utils.ts
  nextjs/packages/next/build/webpack/loaders/next-babel-loader.js
  nextjs/packages/next/lib/eslint/runLintCheck.ts
  nextjs/packages/next/lib/find-pages-dir.ts
  nextjs/packages/next/lib/recursive-readdir.ts
  nextjs/packages/next/package.json
  nextjs/packages/next/server/hot-reloader.ts
  nextjs/packages/next/server/lib/find-page-file.ts
  nextjs/packages/next/server/next-dev-server.ts
  nextjs/packages/next/server/on-demand-entry-handler.ts
  nextjs/test/integration/multi-pages/app/api/api-health.js
  nextjs/test/integration/multi-pages/app/api/hook.spec.js
  nextjs/test/integration/multi-pages/app/not-a-page.js
  nextjs/test/integration/multi-pages/app/pages/_app.js
  nextjs/test/integration/multi-pages/app/pages/home.js
  nextjs/test/integration/multi-pages/app/pages/home.spec.js
  nextjs/test/integration/multi-pages/app/pages/pages/new.js
  nextjs/test/integration/multi-pages/app/pages/users/[id].js
  nextjs/test/integration/multi-pages/app/utils/not-a-page.js
  nextjs/test/integration/multi-pages/pages/api/hello-api.js
  nextjs/test/integration/multi-pages/pages/api/v1/api/launch-api.js
  nextjs/test/integration/multi-pages/pages/api/v1/pages/nested-inside-api-pages.js
  nextjs/test/integration/multi-pages/pages/index.js
  nextjs/test/integration/multi-pages/pages/nested/1.js
  nextjs/test/integration/multi-pages/pages/pages/nested-inside-pages.js
  nextjs/test/integration/multi-pages/test/index.test.js
  nextjs/test/integration/relay-analytics/test/index.test.js
  nextjs/test/integration/src-dir-support-double-dir/src/pages/hello.js
  nextjs/test/integration/src-dir-support-double-dir/src/pages/world.js
  nextjs/test/integration/src-dir-support-double-dir/test/index.test.js
  nextjs/test/integration/telemetry/test/index.test.js
  nextjs/test/unit/find-page-file.unit.test.js
  nextjs/test/unit/next-babel-loader.unit.test.js
  packages/file-pipeline/src/helpers/route-cache.ts
  packages/server/src/stages/index.ts
  packages/server/src/stages/pages/api.test.ts
  packages/server/src/stages/pages/errors.ts
  packages/server/src/stages/pages/find-duplicates.test.ts
  packages/server/src/stages/pages/index.ts
  packages/server/src/stages/pages/pages-path-transformer.test.ts
  packages/server/src/stages/pages/pages.test.ts
  packages/server/src/stages/rewrite-imports/index.ts
  packages/server/src/stages/rewrite-imports/rewrite-imports.test.ts
  packages/server/test/api-routes.test.ts
  packages/server/test/rules.test.ts
  packages/server/test/vercel-now.test.ts
Labels: status/in-progress

#2532 Next.js Fork Migration: Move blitz.config.(js|ts) support into nextjs core (patch)
  .gitignore
  examples/auth/app/pages/ssr.tsx
  nextjs/packages/next/build/babel/plugins/no-anonymous-default-export.ts
  nextjs/packages/next/build/index.ts
  nextjs/packages/next/build/webpack-config.ts
  nextjs/packages/next/client/normalize-trailing-slash.ts
  nextjs/packages/next/export/index.ts
  nextjs/packages/next/next-server/lib/constants.ts
  nextjs/packages/next/next-server/server/config-shared.ts
  nextjs/packages/next/next-server/server/config-utils-worker.ts
  nextjs/packages/next/next-server/server/config.ts
  nextjs/packages/next/next-server/server/next-server.ts
  nextjs/packages/next/package.json
  nextjs/packages/next/server/lib/utils.ts
  nextjs/test/integration/client-navigation-a11y/test/index.test.js
  nextjs/test/integration/jsconfig-empty/jsconfig.json
  nextjs/test/integration/jsconfig-empty/next.config.js
  nextjs/test/integration/jsconfig-empty/pages/index.js
  nextjs/test/integration/jsconfig-empty/test/index.test.js
  nextjs/test/integration/multi-pages/test/index.test.js
  nextjs/test/integration/no-anon-default-export/test/index.test.js
  nextjs/test/isolated/config.unit.test.js
  nextjs/test/jest-setup-after-env.js
  nextjs/test/lib/next-test-utils.js
  nextjs/test/lib/next-webdriver.js
  package.json
  packages/babel-preset/src/fix-node-file-trace/index.ts
  packages/cli/src/index.ts
  packages/config/src/index.ts
  packages/core/src/server/index.ts
  packages/generator/templates/app/gitignore
  packages/server/src/stages/config/index.ts
  packages/server/src/stages/index.ts
  packages/server/test/api-routes.test.ts
  packages/server/test/build.test.ts
  packages/server/test/dev.test.ts
  packages/server/test/rules.test.ts
  packages/server/test/vercel-now.test.ts
  scripts/renameNextConfigToBlitzConfig.sh
  test/integration/auth-serverless/app/mutations/login.ts
  test/integration/auth-serverless/app/mutations/logout.ts
  test/integration/auth-serverless/app/queries/getAuthenticatedBasic.ts
  test/integration/auth-serverless/app/queries/getNoauthBasic.ts
  test/integration/auth-serverless/babel.config.js
  test/integration/auth-serverless/blitz.config.ts
  test/integration/auth-serverless/db.ts
  test/integration/auth-serverless/pages/_app.tsx
  test/integration/auth-serverless/pages/_document.tsx
  test/integration/auth-serverless/pages/authenticated-query.tsx
  test/integration/auth-serverless/pages/login.tsx
  test/integration/auth-serverless/pages/noauth-query.tsx
  test/integration/auth-serverless/test/index.test.ts
  test/integration/auth-serverless/tsconfig.json
  test/integration/auth-serverless/types.ts
  test/integration/auth/.env.production
  test/integration/auth/blitz.config.ts
  test/integration/auth/test/index.test.ts
  test/integration/queries/test/index.test.ts
  test/jest-setup-after-env.js
  test/lib/blitz-test-utils.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review
