Repository blitz-js/blitz, pull requests merged in 2021-01, with the labels that each got.

#1663 Remove unnecessary log message about git core.excludesFiles (patch)
  packages/server/src/parse-chokidar-rules-from-gitignore.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1662 (newapp) Update a few dependencies including React to `0.0.0-experimental-3310209d0`
  examples/auth/package.json
  examples/fauna/package.json
  examples/no-prisma/package.json
  examples/plain-js/package.json
  examples/store/package.json
  packages/generator/templates/app/package.json
  packages/installer/package.json
  patches/release+6.3.0.patch
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1665 Change a number of dependencies to use ranges to help reduce size of installed node_modules (patch)
  packages/blitz/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/display/package.json
  packages/file-pipeline/package.json
  packages/generator/package.json
  packages/installer/package.json
  packages/repl/package.json
  packages/server/package.json
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1676 Fix bug preventing a semicolon in session publicData
  packages/core/src/utils/tokens.test.ts
  packages/core/src/utils/tokens.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#1673 Add config option for cookie `domain` to sessionMiddleware
  packages/core/src/supertokens.ts
  packages/server/src/supertokens.test.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#1667 Add `SecurePassword` utilities to core so you can remove them from `auth-utils.ts` (minor)
  examples/auth/app/auth/auth-utils.ts
  examples/auth/app/auth/mutations/signup.ts
  examples/auth/package.json
  examples/custom-server/db/db.sqlite
  examples/fauna/app/auth/auth-utils.ts
  examples/fauna/app/auth/mutations/signup.ts
  packages/core/package.json
  packages/core/src/auth-utils.ts
  packages/core/src/index.ts
  packages/core/test/auth-utils.test.ts
  packages/generator/templates/app/app/auth/auth-utils.ts
  packages/generator/templates/app/app/auth/mutations/signup.ts
  packages/generator/templates/app/package.json
Labels: status/in-review

#1685 Add `blitz prisma` CLI command for Prisma 2.13+ support
  packages/cli/src/commands/db.ts
  packages/cli/src/commands/prisma.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1687 Update jest config for a deprecated option
  packages/cli/jest.config.js
  packages/generator/jest.config.js
  packages/installer/jest.config.js
  packages/repl/jest.config.js
Labels: status/in-review

#1695 Pin versions in chakra recipe
  recipes/chakra/index.ts
Labels: status/in-review

#1690 Add some tests to `@blitzjs/installer` (meta)
  packages/installer/package.json
  packages/installer/test/executors/__snapshots__/executor.test.tsx.snap
  packages/installer/test/executors/executor.test.tsx
  yarn.lock
Labels: status/in-review

#1661 Prisma 2.13+ Support: Remove all `blitz db` commands except `blitz db seed` and use prisma CLI directly (major)
  examples/auth/README.md
  examples/auth/db/migrations/.keep
  examples/auth/db/migrations/20200704211726/README.md
  examples/auth/db/migrations/20200704211726/schema.prisma
  examples/auth/db/migrations/20200704211726/steps.json
  examples/auth/db/migrations/20200711145940/README.md
  examples/auth/db/migrations/20200711145940/schema.prisma
  examples/auth/db/migrations/20200711145940/steps.json
  examples/auth/db/migrations/20201214220426_initial_migration/migration.sql
  examples/auth/db/migrations/migrate.lock
  examples/auth/db/seeds.ts
  examples/auth/package.json
  examples/custom-server/.eslintrc.js
  examples/custom-server/README.md
  examples/custom-server/app/components/LabeledTextField.tsx
  examples/custom-server/app/pages/_document.tsx
  examples/custom-server/app/pages/index.test.tsx
  examples/custom-server/app/pages/index.tsx
  examples/custom-server/cypress/index.d.ts
  examples/custom-server/cypress/integration/index.test.ts
  examples/custom-server/cypress/support/commands.ts
  examples/custom-server/cypress/support/helpers.ts
  examples/custom-server/db/db.sqlite
  examples/custom-server/db/index.ts
  examples/custom-server/db/migrations/20201122130934-initial-migration/README.md
  examples/custom-server/db/migrations/20201122130934-initial-migration/schema.prisma
  examples/custom-server/db/migrations/20201122130934-initial-migration/steps.json
  examples/custom-server/db/migrations/20210112001717_initial/migration.sql
  examples/custom-server/db/migrations/migrate.lock
  examples/custom-server/package.json
  examples/fauna/README.md
  examples/fauna/app/pages/index.tsx
  examples/no-prisma/README.md
  examples/plain-js/README.md
  examples/plain-js/app/pages/index.js
  examples/plain-js/package.json
  examples/store/README.md
  examples/store/db/migrations/.keep
  examples/store/db/migrations/20200429140440-init/README.md
  examples/store/db/migrations/20200429140440-init/schema.prisma
  examples/store/db/migrations/20200429140440-init/steps.json
  examples/store/db/migrations/20200801094346-add-dates/README.md
  examples/store/db/migrations/20200801094346-add-dates/schema.prisma
  examples/store/db/migrations/20200801094346-add-dates/steps.json
  examples/store/db/migrations/20201214222620_initial_migration/migration.sql
  examples/store/db/migrations/migrate.lock
  examples/store/package.json
  packages/cli/package.json
  packages/cli/src/commands/db.ts
  packages/cli/src/commands/new.ts
  packages/cli/test/commands/console.test.ts
  packages/cli/test/commands/db.test.ts
  packages/cli/test/commands/new.test.ts
  packages/generator/src/generators/model-generator.ts
  packages/generator/templates/app/app/pages/index.tsx
  packages/generator/templates/app/package.json
  packages/server/src/with-blitz.ts
  recipes/render/templates/render.yaml
  yarn.lock
Labels: status/in-review

#1700 Update .eslintrc.js on examples/custom-server to add @typescript-eslint parser/plugin config
  examples/custom-server/.eslintrc.js
  packages/installer/test/executors/executor.test.tsx
  recipes/reflexjs/templates/theme/theme/index.ts
Labels: status/in-review

#1702 Fix extra `ms` in API log message
  packages/server/src/rpc.ts
Labels: status/in-review

#1706 Fix `--help` flag for `blitz prisma` command not being sent to prisma
  packages/cli/src/commands/prisma.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1707 Fix new apps failing to initialize the database in 0.29.0 (patch)
  packages/cli/package.json
  packages/cli/src/commands/new.ts
  packages/cli/src/commands/prisma.ts
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1709 (newapp) Fix studio package.json script to use new blitz prisma command
  examples/auth/package.json
  examples/custom-server/package.json
  examples/fauna/package.json
  packages/generator/templates/app/package.json
Labels: status/in-review

#1716 Fix blitz compiler to ignore sqlite files (patch)
  examples/custom-server/db/db.sqlite
  packages/server/src/config.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1718 Fix: `blitz db seed` should not run prisma migrations
  packages/cli/src/commands/db.ts
Labels: status/in-review

#1717 Fix logout not triggering re-renders for all queries (patch)
  packages/core/src/public-data-store.test.ts
  packages/core/src/public-data-store.ts
  packages/core/src/rpc.ts
  packages/core/src/use-query-hooks.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1721 Add `generateToken()` and `hash256()` utilities (#1721) (minor)
  packages/core/src/auth-utils.ts
  packages/core/src/index.ts
  packages/server/src/supertokens.ts
  packages/server/src/with-blitz.ts
Labels: status/in-review

#1722 Remove console.log from reflexjs recipe
  recipes/reflexjs/index.ts
Labels: status/in-review

#1719 Change `blitz generate` to generate all pages in `app/pages/` and update new app structure with `app/core/`
  packages/generator/src/generator.ts
  packages/generator/src/generators/app-generator.ts
  packages/generator/src/generators/page-generator.ts
  packages/generator/templates/app/README.md
  packages/generator/templates/app/app/api/.keep
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/auth/components/SignupForm.tsx
  packages/generator/templates/app/app/auth/pages/login.tsx
  packages/generator/templates/app/app/auth/pages/signup.tsx
  packages/generator/templates/app/app/components/.keep
  packages/generator/templates/app/app/core/hooks/useCurrentUser.ts
  packages/generator/templates/app/app/core/layouts/Layout.tsx
  packages/generator/templates/app/app/layouts/.keep
  packages/generator/templates/app/app/pages/index.test.tsx
  packages/generator/templates/app/app/pages/index.tsx
  packages/generator/templates/app/test/.keep
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
Labels: status/in-review

#1720 Add `makeServerOnlyPrisma()` utility, allow `db` in client bundle, and update new app template
  examples/auth/db/index.ts
  examples/custom-server/db/index.ts
  examples/store/db/index.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/prisma-utils.ts
  packages/generator/templates/app/db/index.ts
  packages/server/src/with-blitz.ts
Labels: status/in-review

#1726 Fix `makeServerOnlyPrisma()` not working in Jest tests (patch)
  packages/core/src/prisma-utils.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1728 Add @malkomalko as L1 Maintainer
  README.md
Labels: status/in-review

#1725 Drastically simplify Jest integration with a Blitz jest preset and by moving test dependencies into blitz.
  examples/auth/jest.config.js
  examples/auth/package.json
  examples/auth/test/setup.ts
  examples/custom-server/jest.config.js
  examples/custom-server/test/__mocks__/fileMock.js
  examples/custom-server/test/setup.ts
  packages/blitz/jest-preset.js
  packages/blitz/jest-preset/file-mock.js
  packages/blitz/jest-preset/global-setup.js
  packages/blitz/jest-preset/identity-obj-proxy.js
  packages/blitz/jest-preset/setup-after-env.js
  packages/blitz/package.json
  packages/generator/templates/app/README.md
  packages/generator/templates/app/jest.config.js
  packages/generator/templates/app/package.json
  packages/generator/templates/app/test/__mocks__/fileMock.js
  packages/generator/templates/app/test/setup.ts
  yarn.lock
Labels: status/in-review

#1727 Fix `blitz generate` bug when model name ends with number
  packages/cli/src/commands/generate.ts
  packages/generator/src/generators/form-generator.ts
  packages/generator/src/generators/mutation-generator.ts
  packages/generator/src/generators/page-generator.ts
  packages/generator/src/generators/queries-generator.ts
  packages/generator/src/generators/query-generator.ts
  packages/generator/src/index.ts
  packages/generator/src/prisma/field.ts
  packages/generator/src/prisma/model.ts
  packages/generator/src/utils/inflector.ts
  packages/generator/src/utils/kebab-case.ts
  packages/generator/test/utils/inflector.test.ts
  packages/generator/test/utils/kebab-case.test.ts
Labels: status/in-review

#1734 Add `.yalc` folder to ignore paths
  packages/server/src/config.ts
Labels: status/in-review

#1735 Automatically disable `useQuery` suspense when not using concurrent mode
  packages/config/src/index.ts
  packages/core/package.json
  packages/core/src/blitz-data.tsx
  packages/core/src/blitz-script.tsx
  packages/core/src/index.ts
  packages/core/src/types.ts
  packages/core/src/use-query-hooks.ts
  packages/core/src/utils/react-query-utils.ts
  packages/core/test/blitz-data.test.ts
  packages/core/test/use-query.test.tsx
  yarn.lock
Labels: status/in-review

#1740 (newapp) Remove `app/auth/auth-utils.ts` by moving code into the login mutation
  examples/auth/app/auth/auth-utils.ts
  examples/auth/app/auth/mutations/login.ts
  packages/generator/templates/app/README.md
  packages/generator/templates/app/app/auth/auth-utils.ts
  packages/generator/templates/app/app/auth/mutations/login.ts
Labels: status/in-review

#1741 (newapp) Add `changePassword` mutation
  packages/generator/templates/app/README.md
  packages/generator/templates/app/app/auth/mutations/changePassword.ts
  packages/generator/templates/app/app/auth/validations.ts
Labels: status/in-review

#1743 Change session cookies to have a unique prefixed based on package.json name field (major)
  packages/config/src/index.ts
  packages/config/src/node.d.ts
  packages/core/src/blitz-data.tsx
  packages/core/src/constants.ts
  packages/core/src/index.ts
  packages/core/src/public-data-store.test.ts
  packages/core/src/public-data-store.ts
  packages/core/src/supertokens.ts
  packages/core/src/types.ts
  packages/core/test/rpc.test.ts
  packages/core/test/use-query.test.tsx
  packages/server/src/routes.ts
  packages/server/src/supertokens.test.ts
  packages/server/src/supertokens.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1748 Fix all queries not being refetched on login (patch)
  packages/core/src/constants.ts
  packages/core/src/rpc.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#1749 Drastically simplify eslint integration with new eslint-config-blitz package
  examples/auth/.eslintrc.js
  examples/auth/package.json
  examples/store/.eslintrc.js
  packages/blitz/package.json
  packages/eslint-config/.gitignore
  packages/eslint-config/README.md
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/generator/templates/app/.eslintrc.js
  packages/generator/templates/app/package.json
  yarn.lock
Labels: status/in-review

#1753 Update jest preset to runInBand and auto disconnect Prisma client after tests (minor)
  packages/blitz/jest-preset.js
  packages/blitz/jest-preset/setup-after-env.js
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1731 Unify spelling of `TypeScript` (meta)
  README.md
  examples/fauna/jest.config.js
  packages/blitz/jest-preset.js
  packages/cli/src/commands/console.ts
  packages/cli/src/commands/generate.ts
  packages/server/register/launch-editor.js
  packages/server/src/build.ts
  packages/server/src/config.ts
  packages/server/src/dev.ts
  packages/server/src/routes.ts
  packages/server/src/stages/index.ts
  packages/server/src/stages/rpc/index.ts
  rfc-docs/01-architecture.md
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1759 Update `blitz generate` templates for Prisma 2.15 AND update newapp/examples to Prisma 2.15
  examples/auth/app/users/queries/getUser.ts
  examples/auth/app/users/queries/getUsers.ts
  examples/auth/package.json
  examples/custom-server/app/auth/auth-utils.ts
  examples/custom-server/app/users/queries/getCurrentUser.ts
  examples/custom-server/package.json
  examples/plain-js/package.json
  examples/store/app/products/components/ProductForm.tsx
  examples/store/app/products/mutations/createProduct.ts
  examples/store/app/products/mutations/deleteProduct.ts
  examples/store/app/products/mutations/updateProduct.ts
  examples/store/app/products/queries/getProduct.ts
  examples/store/app/products/queries/getProducts.ts
  examples/store/package.json
  packages/cli/package.json
  packages/generator/templates/app/package.json
  packages/generator/templates/queries/get__ModelName__.ts
  packages/generator/templates/queries/get__ModelNames__.ts
  yarn.lock
Labels: status/in-review

#1761 Fix relative imports from within API routes (patch)
  packages/server/src/stages/pages/index.ts
  packages/server/src/stages/relative/index.ts
  packages/server/src/stages/relative/relative.test.ts
Labels: status/in-review

#1762 Change `makeServerOnlyPrisma` to `enhancePrisma` which adds `db.$reset()` for use in tests
  examples/auth/db/index.ts
  examples/custom-server/db/index.ts
  examples/store/db/index.ts
  package.json
  packages/blitz/jest-preset/setup-after-env.js
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/prisma-utils.ts
  packages/core/src/types.ts
  packages/generator/templates/app/db/index.ts
  packages/server/src/with-blitz.ts
  yarn.lock
Labels: status/in-review

#1127 🎉 Add Forgot Password code to new app template
  packages/generator/jest.config.js
  packages/generator/templates/app/.env
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/auth/mutations/forgotPassword.test.ts
  packages/generator/templates/app/app/auth/mutations/forgotPassword.ts
  packages/generator/templates/app/app/auth/mutations/login.ts
  packages/generator/templates/app/app/auth/mutations/logout.ts
  packages/generator/templates/app/app/auth/mutations/resetPassword.test.ts
  packages/generator/templates/app/app/auth/mutations/resetPassword.ts
  packages/generator/templates/app/app/auth/mutations/signup.ts
  packages/generator/templates/app/app/auth/pages/forgot-password.tsx
  packages/generator/templates/app/app/auth/pages/reset-password.tsx
  packages/generator/templates/app/app/auth/validations.ts
  packages/generator/templates/app/db/schema.prisma
  packages/generator/templates/app/mailers/.keep
  packages/generator/templates/app/mailers/forgotPasswordMailer.ts
  packages/generator/templates/app/package.json
  packages/server/src/next-utils.ts
Labels: status/in-review

#1765 Fix API duration log to include serialization time AND add log serialization duration at DEBUG log level (patch)
  examples/store/blitz.config.js
  packages/server/src/rpc.ts
Labels: status/in-review

#1766 Fix prisma errors missing code & meta properties
  packages/core/package.json
  packages/core/src/errors.ts
  packages/core/src/rpc.ts
  packages/server/package.json
  packages/server/src/rpc.ts
  yarn.lock
Labels: status/in-review

#1764 Add Quirrel recipe AND add Plain-Text Transformer to recipe APIs
  .eslintrc.js
  packages/installer/src/executors/file-transform-executor.tsx
  packages/installer/src/utils/paths.ts
  packages/installer/src/utils/transform.ts
  recipes/quirrel/index.ts
  recipes/quirrel/package.json
  recipes/quirrel/templates/app/api/greetingsQueue.ts
  recipes/quirrel/templates/app/api/hourlyCron.ts
  recipes/quirrel/templates/app/mutations/enqueueGreeting.ts
Labels: kind/feature-change, kind/recipe, scope/installer, status/in-review

#1770 Fix type of `enhancePrisma` constructor args
  packages/core/src/prisma-utils.ts
Labels: status/in-review

#1772 Add missing type exports like `GetStaticPropsContext` (patch)
  examples/auth/blitz.config.js
  examples/store/blitz.config.js
  packages/core/src/index.ts
  packages/core/src/types.ts
  packages/core/test/rpc.test.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1773 Change package.json engines version 12.20 to 12
  package.json
Labels: status/in-review

#1771 Add `blitz/babel` preset which includes `babel-plugin-superjson-next`
  examples/auth/babel.config.js
  examples/custom-server/babel.config.js
  examples/fauna/babel.config.js
  examples/store/app/products/pages/products/[handle].tsx
  examples/store/app/products/pages/products/index.tsx
  examples/store/app/products/pages/products/ssr.tsx
  examples/store/babel.config.js
  package.json
  packages/babel-preset/.gitignore
  packages/babel-preset/README.md
  packages/babel-preset/package.json
  packages/babel-preset/src/index.ts
  packages/babel-preset/test/blah.test.ts
  packages/babel-preset/tsconfig.json
  packages/blitz/babel.js
  packages/blitz/package.json
  packages/generator/templates/app/babel.config.js
  recipes/emotion/index.ts
  yarn.lock
Labels: status/in-review

#1778 Change normal resolver logging to log serializer duration (minor)
  packages/server/src/rpc.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1775 Rename `chakra` recipe to `chakra-ui`
  recipes/chakra-ui/index.ts
  recipes/chakra-ui/package.json
Labels: status/in-review

#1780 docs: Add READMEs to packages that were missing them
  packages/cli/README.md
  packages/config/README.md
  packages/core/README.md
Labels: status/in-review

#1779 [RFC] Prefix all `ctx.session` methods with `$` and move `publicData` fields to top level of `ctx.session`
  examples/auth/app/auth/mutations/login.ts
  examples/auth/app/auth/mutations/logout.ts
  examples/auth/app/auth/mutations/signup.ts
  examples/auth/app/users/mutations/trackView.ts
  examples/auth/app/users/queries/getUser.ts
  examples/auth/app/users/queries/getUsers.ts
  examples/custom-server/app/auth/mutations/login.ts
  examples/custom-server/app/auth/mutations/logout.ts
  examples/custom-server/app/auth/mutations/signup.ts
  examples/fauna/app/auth/mutations/login.ts
  examples/fauna/app/auth/mutations/logout.ts
  examples/fauna/app/auth/mutations/signup.ts
  packages/core/src/passport-adapter.ts
  packages/core/src/supertokens.ts
  packages/server/src/supertokens.test.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#1789 Fix blitz/babel preset not passing options through to next/babel
  packages/babel-preset/src/index.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1782 Major improvement to `blitz install` UX
  packages/installer/src/executors/add-dependency-executor.tsx
  packages/installer/src/executors/executor.tsx
  packages/installer/src/executors/file-transform-executor.tsx
  packages/installer/src/executors/new-file-executor.tsx
  packages/installer/src/recipe-executor.tsx
  packages/installer/src/recipe-renderer.tsx
  recipes/base-web/index.ts
  recipes/chakra-ui/index.ts
  recipes/emotion/index.ts
  recipes/material-ui/index.ts
  recipes/quirrel/index.ts
  recipes/reflexjs/index.ts
  recipes/tailwind/index.ts
  recipes/theme-ui/index.ts
Labels: status/in-review

#1790 Fix `blitz generate` folder names to be kebab-case
  packages/generator/src/generators/form-generator.ts
  packages/generator/src/generators/mutation-generator.ts
  packages/generator/src/generators/queries-generator.ts
Labels: status/in-review

#1686 Fix `blitz console` not working in vanilla JS projects
  packages/cli/package.json
  packages/repl/src/utils/module.ts
  yarn.lock
Labels: status/in-review

#1800 Updated all <Form> templates to make submitText optional
  examples/auth/app/components/Form.tsx
  examples/custom-server/app/components/Form.tsx
  examples/fauna/app/components/Form.tsx
  packages/generator/templates/app/_forms/finalform/Form.tsx
  packages/generator/templates/app/_forms/formik/Form.tsx
  packages/generator/templates/app/_forms/hookform/Form.tsx
Labels: status/in-review

#1799 inject isAuthorized args type
  examples/auth/types.ts
  package.json
  packages/core/src/index.ts
  packages/core/src/supertokens.ts
  packages/core/src/types.ts
  packages/server/src/supertokens.ts
  yarn.lock
Labels: status/in-review

#1796 Improvements to `isAuthorized`: (1) Ability to strongly type, (2) Change first arg to have `ctx`, (3) Allow multiple params, (4) add conditional `$authorize()`
  examples/auth/types.ts
  package.json
  packages/core/src/index.ts
  packages/core/src/supertokens.ts
  packages/core/src/types.ts
  packages/generator/templates/app/types.ts
  packages/server/src/supertokens.test.ts
  packages/server/src/supertokens.ts
  yarn.lock
Labels: status/in-review

#1801 Add `pipe.resolver()`, `pipe.zod()`, `pipe.authorize()`, and `pipe.authorizeIf()` for queries/mutations
  examples/auth/app/auth/mutations/login.ts
  examples/auth/app/auth/mutations/signup.ts
  examples/auth/app/pages/projects/new.tsx
  examples/auth/app/projects/mutations/createProject.ts
  examples/auth/app/users/mutations/trackView.ts
  examples/auth/db/migrations/20210123205208_add_projects/migration.sql
  examples/auth/db/migrations/20210126232902_add_project_due_date/migration.sql
  examples/auth/db/migrations/migration_lock.toml
  examples/auth/db/schema.prisma
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/pipes.ts
  yarn.lock
Labels: status/in-review

#1806 Simplify type definition for `PublicData` (breaking change)
  examples/auth/types.ts
  examples/custom-server/types.ts
  examples/fauna/types.ts
  packages/core/src/index.ts
  packages/core/src/public-data-store.ts
  packages/core/src/supertokens.ts
  packages/core/src/types.ts
  packages/core/src/utils/tokens.test.ts
  packages/generator/templates/app/types.ts
  packages/server/src/supertokens.test.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#1808 Fix to properly handle http errors (no more `Failed to parse json from request to /api/users/queries/getCurrentUser`) (patch)
  packages/core/src/rpc.ts
  packages/core/test/rpc.test.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1809 Fix `session.$isAuthorized` to not have assertion return type (patch)
  packages/core/src/supertokens.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1810 Fix new app and `blitz generate` templates to use new `session.$` prefix (patch)
  packages/generator/templates/app/app/auth/mutations/changePassword.ts
  packages/generator/templates/app/app/auth/mutations/login.ts
  packages/generator/templates/app/app/auth/mutations/logout.ts
  packages/generator/templates/app/app/auth/mutations/signup.ts
  packages/generator/templates/app/test/setup.ts
  packages/generator/templates/mutation/create__ModelName__.ts
  packages/generator/templates/mutation/delete__ModelName__.ts
  packages/generator/templates/mutation/update__ModelName__.ts
  packages/generator/templates/queries/get__ModelName__.ts
  packages/generator/templates/queries/get__ModelNames__.ts
  packages/generator/templates/query/__rawInput__.ts
Labels: status/in-review

#1811 (newapp) update mutations to use the new pipe functions
  packages/generator/package.json
  packages/generator/templates/app/app/auth/components/LoginForm.tsx
  packages/generator/templates/app/app/auth/components/SignupForm.tsx
  packages/generator/templates/app/app/auth/mutations/changePassword.ts
  packages/generator/templates/app/app/auth/mutations/forgotPassword.test.ts
  packages/generator/templates/app/app/auth/mutations/forgotPassword.ts
  packages/generator/templates/app/app/auth/mutations/login.ts
  packages/generator/templates/app/app/auth/mutations/resetPassword.ts
  packages/generator/templates/app/app/auth/mutations/signup.ts
  packages/generator/templates/app/app/auth/pages/forgot-password.tsx
  packages/generator/templates/app/app/auth/pages/reset-password.tsx
  packages/generator/templates/app/app/auth/validations.ts
Labels: status/in-review

#1821 Rename resolver pipe fns: `pipe.resolver` to `resolver.pipe`, `pipe.zod` to `resolver.zod`, etc
  examples/auth/app/auth/mutations/login.ts
  examples/auth/app/auth/mutations/signup.ts
  examples/auth/app/projects/mutations/createProject.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/resolver.ts
  packages/generator/templates/app/app/auth/mutations/changePassword.ts
  packages/generator/templates/app/app/auth/mutations/forgotPassword.ts
  packages/generator/templates/app/app/auth/mutations/login.ts
  packages/generator/templates/app/app/auth/mutations/resetPassword.ts
  packages/generator/templates/app/app/auth/mutations/signup.ts
  yarn.lock
Labels: status/in-review

#1822 Fix type of resolver.pipe when one of the pipe functions returns a promise
  packages/core/src/resolver.ts
  packages/core/src/types.ts
Labels: status/in-review

#1823 Fix broken API routes because of babel-plugin-superjson-next bug (patch)
  packages/babel-preset/package.json
  yarn.lock
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1824 Remove `resolver.authorizeIf` AND remove second options arg to `session.$authorize()` (major)
  examples/auth/app/projects/mutations/createProject.ts
  packages/core/src/resolver.ts
  packages/server/src/supertokens.ts
Labels: status/in-review

#1815 Fix `blitz install` error message when recipe doesn't exist (patch)
  packages/cli/src/commands/install.ts
Labels: 0 - <(^_^)> - merge it! ✌️, status/in-review

#1831 Fix `resolver.authorize(` doesn't work as type guard (with great effort)
  packages/core/src/resolver.ts
Labels: status/in-review

#1833 (newapp) update `_app.tsx` to use new `ErrorFallbackProps` for better typing
  packages/generator/templates/app/app/pages/_app.tsx
Labels: status/in-review

#1834 Fix bug in `resolver.authorize()` type
  examples/auth/app/projects/mutations/createProject.ts
  packages/core/src/resolver.ts
Labels: status/in-review
