Repository blitz-js/blitz, pull requests merged in 2022-10, with the labels that each got.

#3877 refactor(js-templates): remove {} from single values inside package.json
  .changeset/orange-mirrors-tap.md
  packages/generator/templates/app/package.js.json
  packages/generator/templates/minimalapp/package.js.json
Labels: status/in-review

#3872 fix: remove views from public Session data
  .changeset/strong-keys-lie.md
  packages/generator/templates/app/types.ts
  pnpm-lock.yaml
Labels: status/in-review

#3701 fix detecting `blitz.config.(ts|js)` config file
  .changeset/spotty-lies-visit.md
  packages/codemod/src/upgrade-legacy.ts
Labels: status/in-review

#3874 Try to load prisma.schema path from pkg json
  .changeset/empty-pants-search.md
  packages/generator/src/generators/model-generator.ts
Labels: status/in-review, hacktoberfest-accepted

#3876 Created the requested settings.json file
  .vscode/settings.json
Labels: status/in-review, no-changeset

#3882 update prisma-ast version in blitz generator package
  .changeset/blue-flowers-peel.md
  packages/generator/package.json
  pnpm-lock.yaml
Labels: status/in-review, hacktoberfest-accepted

#3890 Migrate Routes Command
  .changeset/few-shrimps-leave.md
  packages/blitz/src/cli/commands/routes.ts
  packages/blitz/src/cli/index.ts
  packages/blitz/src/cli/utils/next-console.ts
  packages/blitz/src/cli/utils/routes-manifest.ts
Labels: status/in-review

#3728 Fix queryKeyGeneration when using invalidateQuery
  .changeset/tame-pumpkins-nail.md
  .changeset/thirty-spies-applaud.md
  integration-tests/react-query-utils/app/queries/getSequence.ts
  integration-tests/react-query-utils/pages/page-with-invalidate.tsx
  integration-tests/react-query-utils/test/index.test.ts
  packages/blitz-rpc/src/data-client/react-query-utils.test.ts
  packages/blitz-rpc/src/data-client/react-query-utils.ts
  pnpm-lock.yaml
  recipes/ghost/templates/pages/ghost/post/[slug].tsx
Labels: status/in-review

#3885 Add `blitz export` command
  .changeset/itchy-houses-marry.md
  packages/blitz/src/cli/commands/next/export.ts
  packages/blitz/src/cli/commands/next/index.ts
  packages/blitz/src/cli/index.ts
  packages/blitz/src/cli/utils/config.ts
  packages/blitz/src/cli/utils/next-commands.ts
  packages/blitz/src/cli/utils/next-utils.ts
Labels: status/in-review

#3878 Update PULL_REQUEST_TEMPLATE.md
  .changeset/gentle-lions-explode.md
  .github/PULL_REQUEST_TEMPLATE.md
  pnpm-lock.yaml
Labels: status/in-review, no-changeset

#3895 Fix missing `blitz/installer` dependency in recipes
  .changeset/hungry-pens-collect.md
  packages/blitz/package.json
  pnpm-lock.yaml
Labels: status/in-review

#3866 #3748 Add custom template option back to blitz generate command
  .changeset/slow-impalas-tap.md
  apps/toolkit-app/app/blitz-server.ts
  packages/blitz/src/cli/commands/generate.ts
  packages/blitz/src/types.ts
  packages/generator/src/generator.ts
Labels: status/in-review

#3906 Upgrade CI Syntax
  .github/workflows/changeset_check.yml
  .github/workflows/main.yml
  pnpm-lock.yaml
Labels: status/in-review, no-changeset

#3898 fix(rpc): allow return undefined in setQueryData updater function
  .changeset/khaki-ducks-cheer.md
  packages/blitz-rpc/src/data-client/react-query-utils.ts
Labels: status/in-review

#3910 Upgrade eslint-config-next in new app templates to fix linting issues on blitz build
  .changeset/lucky-years-turn.md
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  packages/blitz/src/cli/utils/next-console.ts
  packages/config/package.json
  packages/generator/templates/app/package.js.json
  packages/generator/templates/app/package.ts.json
  packages/generator/templates/minimalapp/package.js.json
  packages/generator/templates/minimalapp/package.ts.json
  pnpm-lock.yaml
Labels: status/in-review

#3886 Add BlitzLogger plugin and allow customizing logging
  .changeset/giant-mails-tap.md
  apps/toolkit-app-passportjs/app/blitz-server.ts
  apps/toolkit-app/app/blitz-server.ts
  apps/toolkit-app/pages/index.tsx
  apps/web/app/blitz-server.ts
  integration-tests/auth/app/blitz-server.ts
  integration-tests/get-initial-props/app/blitz-server.ts
  integration-tests/middleware/app/blitz-server.ts
  integration-tests/no-suspense/app/blitz-server.ts
  integration-tests/react-query-utils/app/blitz-server.ts
  integration-tests/trailing-slash/app/blitz-server.ts
  packages/blitz-next/src/index-server.ts
  packages/blitz/src/index-server.ts
  packages/blitz/src/logging.ts
  packages/blitz/src/middleware.ts
  packages/generator/templates/app/app/blitz-server.ts
  pnpm-lock.yaml
Labels: status/in-review

#3912 Fix 'ambiguous class detected' errors
  .changeset/little-pears-ring.md
  packages/blitz/src/index-browser.tsx
Labels: status/in-review

#3915 Remove unnecessary `as number` assertions from new app templates
  .changeset/chilly-nails-nail.md
  apps/toolkit-app-passportjs/app/auth/mutations/changePassword.ts
  apps/toolkit-app-passportjs/app/users/queries/getCurrentUser.ts
  apps/toolkit-app/app/auth/mutations/changePassword.ts
  apps/toolkit-app/app/users/queries/getCurrentUser.ts
  packages/generator/templates/app/app/auth/mutations/changePassword.ts
  packages/generator/templates/app/app/users/queries/getCurrentUser.ts
  pnpm-lock.yaml
Labels: status/in-review

#3888 Custom Server TS error
  .changeset/moody-spoons-rhyme.md
  packages/blitz/src/cli/utils/next-utils.ts
  pnpm-lock.yaml
Labels: status/in-review

#3922 Fix reset token being undefined when passed to the resetPassword mutation
  .changeset/lemon-pillows-switch.md
  apps/toolkit-app/pages/auth/reset-password.tsx
  packages/generator/templates/app/pages/auth/reset-password.tsx
Labels: status/in-review

#3919 Update recipes
  pnpm-lock.yaml
  recipes/base-web/index.ts
  recipes/base-web/templates/utils/styletron.ts
  recipes/bumbag-ui/index.ts
  recipes/logrocket/index.ts
  recipes/logrocket/package.json
  recipes/material-ui/index.ts
  recipes/material-ui/templates/pages/_document.tsx
  recipes/next-ui/index.ts
  recipes/passenger/templates/passenger.js
  recipes/quirrel/index.ts
  recipes/quirrel/templates/app/mutations/enqueueGreeting.ts
  recipes/quirrel/templates/pages/api/greetingsQueue.ts
  recipes/quirrel/templates/pages/api/hourlyCron.ts
  recipes/reflexjs/index.ts
  recipes/reflexjs/templates/babel.config.js
  recipes/secureheaders/index.ts
  recipes/styled-components/index.ts
  recipes/styled-components/templates/babel.config.js
  recipes/theme-ui/index.ts
  recipes/vanilla-extract/index.ts
Labels: status/in-review, no-changeset

#3909 Fix Blitz Install
  .changeset/honest-comics-vanish.md
  packages/blitz/package.json
  packages/blitz/src/cli/commands/install.ts
  pnpm-lock.yaml
  recipes/base-web/index.ts
  recipes/base-web/package.json
  recipes/base-web/templates/utils/styletron.ts
  recipes/bulma/package.json
  recipes/bumbag-ui/index.ts
  recipes/bumbag-ui/package.json
  recipes/chakra-ui/package.json
  recipes/emotion/package.json
  recipes/gh-action-yarn-mariadb/package.json
  recipes/gh-action-yarn-postgres/package.json
  recipes/ghost/package.json
  recipes/graphql-apollo-server/package.json
  recipes/logrocket/index.ts
  recipes/logrocket/package.json
  recipes/material-ui/index.ts
  recipes/material-ui/package.json
  recipes/material-ui/templates/pages/_document.tsx
  recipes/next-ui/index.ts
  recipes/next-ui/package.json
  recipes/passenger/package.json
  recipes/passenger/templates/passenger.js
  recipes/quirrel/index.ts
  recipes/quirrel/package.json
  recipes/quirrel/templates/app/mutations/enqueueGreeting.ts
  recipes/quirrel/templates/pages/api/greetingsQueue.ts
  recipes/quirrel/templates/pages/api/hourlyCron.ts
  recipes/reflexjs/index.ts
  recipes/reflexjs/package.json
  recipes/reflexjs/templates/babel.config.js
  recipes/render/package.json
  recipes/secureheaders/index.ts
  recipes/secureheaders/package.json
  recipes/stitches/package.json
  recipes/styled-components/index.ts
  recipes/styled-components/package.json
  recipes/styled-components/templates/babel.config.js
  recipes/tailwind/package.json
  recipes/theme-ui/index.ts
  recipes/theme-ui/package.json
  recipes/vanilla-extract/index.ts
  recipes/vanilla-extract/package.json
Labels: status/in-progress

#3928 Export `enhancePrisma` from the server entry point
  .changeset/silent-lies-run.md
  packages/blitz/src/index-browser.tsx
  packages/blitz/src/index-server.ts
  packages/blitz/src/utils/enhance-prisma.ts
  pnpm-lock.yaml
Labels: status/in-review

#3891 Add GET support to RPC specification
  .changeset/itchy-cups-double.md
  apps/toolkit-app/app/users/queries/getCurrentUser.ts
  integration-tests/rpc/app/queries/getBasicWithGET.js
  integration-tests/rpc/test/index.test.js
  packages/blitz-rpc/package.json
  packages/blitz-rpc/src/data-client/rpc.ts
  packages/blitz-rpc/src/index-server.ts
  packages/blitz-rpc/src/loader-client.ts
  packages/blitz-rpc/src/loader-server.ts
  packages/blitz-rpc/src/parse-rpc-config.ts
  packages/blitz/src/types.ts
  pnpm-lock.yaml
Labels: status/in-review
