Repository blitz-js/blitz, pull requests merged in 2022-12, with the labels that each got.

#3995 Fix blitz install for recipes that use the path helper
  .changeset/rude-trainers-visit.md
  packages/blitz/src/installer/utils/paths.ts
Labels: status/in-review

#4006 fix: Reject db.() with an error object
  .changeset/calm-papayas-protect.md
  packages/blitz/src/utils/enhance-prisma.ts
Labels: status/in-review

#4008 fix Cannot read properties of null (reading 'isReady') for pnpm/yarn v3
  .changeset/khaki-pens-rest.md
  .github/CODEOWNERS
  packages/blitz-auth/build.config.ts
  packages/blitz-auth/package.json
  packages/blitz-next/build.config.ts
  packages/blitz-next/package.json
  packages/blitz-rpc/build.config.ts
  packages/blitz-rpc/package.json
  pnpm-lock.yaml
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#3984 Remove husky prepush hook & update precommit hook to only run prettier
  .changeset/chilly-candles-care.md
  packages/blitz/src/utils/enhance-prisma.ts
  packages/generator/src/generators/app-generator.ts
  packages/generator/templates/app/.husky/pre-commit
  packages/generator/templates/app/.husky/pre-push-js
  packages/generator/templates/app/.husky/pre-push-ts
  packages/generator/templates/minimalapp/.husky/pre-commit
  packages/generator/templates/minimalapp/.husky/pre-push-js
  packages/generator/templates/minimalapp/.husky/pre-push-ts
  pnpm-lock.yaml
Labels: status/in-review

#3899 support invalidate all queries
  .changeset/stupid-rabbits-jump.md
  packages/blitz-rpc/src/data-client/react-query-utils.ts
Labels: status/in-review

#3892 feat(cli): add href property to RouteURLObject
  .changeset/thick-moons-fry.md
  .github/workflows/main.yml
  packages/blitz-next/src/index-browser.tsx
  packages/blitz/src/cli/utils/routes-manifest.ts
  packages/blitz/src/installer/executors/run-command-executor.tsx
  packages/blitz/src/types.ts
  pnpm-lock.yaml
Labels: status/in-review

#4016 SignupForm.tsx: Improve helper comment
  apps/toolkit-app/src/auth/components/SignupForm.tsx
Labels: status/in-review, no-changeset

#4009 React Suspense on Next 13 patch fix
  .changeset/three-toes-sell.md
  packages/blitz/src/cli/utils/codegen-tasks.ts
Labels: status/in-review

#4018 Update README.md|s to use `src/` instead of `app/`
  apps/toolkit-app-passportjs/README.md
  apps/toolkit-app/README.md
  packages/generator/templates/app/README.md
  packages/generator/templates/minimalapp/README.md
Labels: status/in-review, no-changeset

#4019 Reference `vitest.config.ts` instead of jest for README|s
  apps/toolkit-app/README.md
  packages/generator/templates/app/README.md
  packages/generator/templates/minimalapp/README.md
Labels: status/in-review, no-changeset
