Repository blitz-js/blitz, pull requests merged in 2023-09, with the labels that each got.

#4211 fixes: Blitz template
  .changeset/shaggy-boxes-exercise.md
  .github/workflows/main.yml
  integration-tests/auth-with-rpc/test/index.test.ts
  packages/blitz-next/package.json
  packages/blitz/src/cli/commands/new.ts
  packages/generator/templates/app/package.ts.json
  packages/generator/templates/validations/schemas.ts
  pnpm-lock.yaml
Labels: status/in-review

#4209 Add .tsx & .jsx file extensions for resolvers
  .changeset/nice-cats-lay.md
  packages/blitz-rpc/src/server/loader/server/loader-server.ts
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4208 Fix for tslog error logging
  .changeset/nervous-shrimps-serve.md
  packages/blitz-rpc/src/index-server.ts
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4214 feat(cli): remove unnecessary language selector step
  .changeset/little-cycles-hang.md
  packages/blitz/src/cli/commands/new.ts
  pnpm-lock.yaml
Labels: status/in-review

#4215 Remove rouge `console.log` from codegen
  .changeset/quick-crews-occur.md
  packages/blitz/src/cli/utils/codegen-tasks.ts
Labels: status/in-review

#4220 [Internal] Update fc logo
  assets/flightcontrol.png
Labels: status/in-review, no-changeset
