Repository blitz-js/blitz, pull requests merged in 2023-08, with the labels that each got.

#4196 Fix CI: remove workspace from package.json
  .github/workflows/main.yml
  apps/next13/package.json
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  apps/web/package.json
  integration-tests/auth-with-rpc/package.json
  integration-tests/auth/package.json
  integration-tests/auth/test/index.test.ts
  integration-tests/get-initial-props/package.json
  integration-tests/middleware/package.json
  integration-tests/next-13-app-dir/package.json
  integration-tests/no-suspense/package.json
  integration-tests/qm/package.json
  integration-tests/react-query-utils/package.json
  integration-tests/rpc-path-root/package.json
  integration-tests/rpc/package.json
  integration-tests/trailing-slash/package.json
  packages/blitz-auth/package.json
  packages/blitz-next/package.json
  packages/blitz-rpc/package.json
  packages/blitz/package.json
  packages/codemod/package.json
  pnpm-lock.yaml
Labels: status/in-review, no-changeset

#4181 docs: add a name column to generate all examples
  .changeset/chilly-jeans-fix.md
  apps/toolkit-app/src/pages/index.tsx
  packages/generator/templates/app/src/pages/index.tsx
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4198 blitz-auth: `useAuthenticatedBlitzContext` returns `AuthenticatedCtx`
  .changeset/fresh-camels-return.md
  packages/blitz-auth/src/server/auth-sessions.ts
  packages/blitz-auth/src/shared/types.ts
  packages/blitz-rpc/src/server/resolvers/resolver.ts
  packages/blitz/src/types.ts
Labels: status/in-review
