Repository blitz-js/blitz, pull requests merged in 2023-04, with the labels that each got.

#4110 Fix invoke type regression
  .changeset/nice-boxes-travel.md
  packages/blitz-rpc/src/client/invoke.ts
Labels: status/in-review

#3997 Fix blitz recipe paths
  .changeset/many-fans-fetch.md
  packages/blitz/src/installer/utils/paths.ts
  pnpm-lock.yaml
  recipes/bumbag-ui/index.ts
  recipes/chakra-ui/index.ts
  recipes/next-ui/index.ts
  recipes/tailwind/templates/config/tailwind.config.js
Labels: status/in-review

#4113 Add toValidSemver utility function
  .changeset/plenty-gifts-provide.md
  packages/blitz/src/cli/utils/codegen-tasks.ts
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4120 Update the version of next in the new template from 13.2 to 13.3.0
  .changeset/ninety-pots-learn.md
  apps/next13/package.json
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  apps/web/package.json
  integration-tests/auth-with-rpc/package.json
  integration-tests/auth-with-rpc/test/index.test.ts
  integration-tests/auth/package.json
  integration-tests/get-initial-props/package.json
  integration-tests/middleware/package.json
  integration-tests/next-13-app-dir/package.json
  integration-tests/no-suspense/package.json
  integration-tests/qm/package.json
  integration-tests/react-query-utils/package.json
  integration-tests/rpc-path-root/package.json
  integration-tests/rpc/package.json
  integration-tests/trailing-slash/package.json
  package.json
  packages/blitz-auth/package.json
  packages/blitz-next/package.json
  packages/blitz-rpc/package.json
  packages/generator/templates/app/package.js.json
  packages/generator/templates/app/package.ts.json
  packages/generator/templates/minimalapp/package.js.json
  packages/generator/templates/minimalapp/package.ts.json
  pnpm-lock.yaml
Labels: status/in-review

#4132 fix (minor): Replace console.log with debug
  packages/blitz/src/cli/utils/routes-manifest.ts
Labels: status/in-review, no-changeset

#4133 Fix: Add missing entry to expose next-auth adapter
  .changeset/wise-lies-relate.md
  packages/blitz-auth/package.json
Labels: status/in-review

#4122 fix: add missing key prop to LabelSelectField
  .changeset/nine-bags-rhyme.md
  packages/generator/templates/app/_forms/finalform/LabelSelectField.tsx
Labels: status/in-review
