Repository blitz-js/blitz, pull requests merged in 2023-01, with the labels that each got.

#4027 fix: fix adding authError query param to redirect url (Passport adapter)
  .changeset/dull-rings-arrive.md
  packages/blitz-auth/src/server/passport-adapter.ts
Labels: status/in-review

#4031 Fix suspense error codegen patch for latest nextjs version
  .changeset/fluffy-coats-flow.md
  packages/blitz-rpc/src/data-client/react-query.tsx
  packages/blitz/package.json
  packages/blitz/src/cli/utils/codegen-tasks.ts
  pnpm-lock.yaml
Labels: status/in-review

#4034 Revert "Version Packages (beta)"
  .changeset/pre.json
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  integration-tests/auth-with-rpc/package.json
  integration-tests/auth/package.json
  integration-tests/get-initial-props/package.json
  integration-tests/middleware/package.json
  integration-tests/no-suspense/package.json
  integration-tests/qm/package.json
  integration-tests/react-query-utils/package.json
  integration-tests/rpc-path-root/package.json
  integration-tests/rpc/package.json
  integration-tests/trailing-slash/package.json
  packages/blitz-auth/CHANGELOG.md
  packages/blitz-auth/package.json
  packages/blitz-next/CHANGELOG.md
  packages/blitz-next/package.json
  packages/blitz-rpc/CHANGELOG.md
  packages/blitz-rpc/package.json
  packages/blitz/CHANGELOG.md
  packages/blitz/package.json
  packages/codemod/CHANGELOG.md
  packages/codemod/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/generator/CHANGELOG.md
  packages/generator/package.json
  packages/pkg-template/package.json
  recipes/base-web/package.json
  recipes/bulma/package.json
  recipes/bumbag-ui/package.json
  recipes/chakra-ui/package.json
  recipes/emotion/package.json
  recipes/gh-action-yarn-mariadb/package.json
  recipes/gh-action-yarn-postgres/package.json
  recipes/ghost/package.json
  recipes/graphql-apollo-server/package.json
  recipes/logrocket/package.json
  recipes/material-ui/package.json
  recipes/next-ui/package.json
  recipes/passenger/package.json
  recipes/quirrel/package.json
  recipes/reflexjs/package.json
  recipes/render/package.json
  recipes/secureheaders/package.json
  recipes/stitches/package.json
  recipes/styled-components/package.json
  recipes/tailwind/package.json
  recipes/theme-ui/package.json
  recipes/vanilla-extract/package.json
Labels: status/in-review

#4035 Version Packages (beta)
  .changeset/pre.json
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  integration-tests/auth-with-rpc/package.json
  integration-tests/auth/package.json
  integration-tests/get-initial-props/package.json
  integration-tests/middleware/package.json
  integration-tests/no-suspense/package.json
  integration-tests/qm/package.json
  integration-tests/react-query-utils/package.json
  integration-tests/rpc-path-root/package.json
  integration-tests/rpc/package.json
  integration-tests/trailing-slash/package.json
  packages/blitz-auth/CHANGELOG.md
  packages/blitz-auth/package.json
  packages/blitz-auth/src/server/passport-adapter.ts
  packages/blitz-next/CHANGELOG.md
  packages/blitz-next/package.json
  packages/blitz-rpc/CHANGELOG.md
  packages/blitz-rpc/package.json
  packages/blitz/CHANGELOG.md
  packages/blitz/package.json
  packages/codemod/CHANGELOG.md
  packages/codemod/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/generator/CHANGELOG.md
  packages/generator/package.json
  packages/pkg-template/package.json
  pnpm-lock.yaml
  recipes/base-web/package.json
  recipes/bulma/package.json
  recipes/bumbag-ui/package.json
  recipes/chakra-ui/package.json
  recipes/emotion/package.json
  recipes/gh-action-yarn-mariadb/package.json
  recipes/gh-action-yarn-postgres/package.json
  recipes/ghost/package.json
  recipes/graphql-apollo-server/package.json
  recipes/logrocket/package.json
  recipes/material-ui/package.json
  recipes/next-ui/package.json
  recipes/passenger/package.json
  recipes/quirrel/package.json
  recipes/reflexjs/package.json
  recipes/render/package.json
  recipes/secureheaders/package.json
  recipes/stitches/package.json
  recipes/styled-components/package.json
  recipes/tailwind/package.json
  recipes/theme-ui/package.json
  recipes/vanilla-extract/package.json
Labels: status/in-review, no-changeset

#4037 fix failed localstorage access to not crash the application
  .changeset/soft-fans-carry.md
  packages/blitz-auth/src/client/index.tsx
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4042 add `currentPassword` to default masked fields in the logger
  .changeset/swift-poets-travel.md
  .kodiak.toml
  packages/blitz/src/logging.ts
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4032 prisma/field: Improve TS guard
  packages/generator/src/prisma/field.ts
Labels: status/in-review, no-changeset

#4044 internal: Fix playwright install issue
  .github/workflows/main.yml
Labels: status/in-review, no-changeset

#4047 internal: fix playwright installation error by fixing version
  .github/workflows/main.yml
Labels: status/in-review, no-changeset

#3987 Redesign the index page for newly generated blitz projects
  .changeset/tricky-kids-press.md
  packages/generator/templates/app/package.js.json
  packages/generator/templates/app/package.ts.json
  packages/generator/templates/app/src/pages/_app.tsx
  packages/generator/templates/app/src/pages/index.tsx
  packages/generator/templates/app/src/styles/Home.module.css
  packages/generator/templates/app/src/styles/globals.css
  packages/generator/templates/minimalapp/package.js.json
  packages/generator/templates/minimalapp/package.ts.json
  packages/generator/templates/minimalapp/src/pages/index.tsx
  packages/generator/templates/minimalapp/src/styles/Home.module.css
  packages/generator/templates/minimalapp/src/styles/globals.css
  pnpm-lock.yaml
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4043 Add missing MockRouter prop in generated test utils
  .changeset/purple-jars-begin.md
  packages/generator/templates/app/test/utils.tsx
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4045 change rpc route basepath includeRPC in monorepos to be one folder up
  .changeset/clean-hounds-laugh.md
  integration-tests/rpc-path-root/next.config.js
  integration-tests/rpc-path-root/test/index.test.js
  packages/blitz-rpc/src/loader-utils.ts
  pnpm-lock.yaml
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4033 Use src instead of app folder for `blitz generate custom-template`
  .changeset/lemon-teachers-jam.md
  apps/toolkit-app/src/blitz-server.ts
  integration-tests/auth-with-rpc/src/blitz-server.ts
  packages/blitz/src/cli/commands/generate.ts
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4039 Update package Zod to 3.20.2
  .changeset/giant-timers-search.md
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  integration-tests/auth-with-rpc/package.json
  packages/blitz-rpc/package.json
  packages/blitz/package.json
  packages/generator/templates/app/package.ts.json
  pnpm-lock.yaml
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4054 Add missing Layout.tsx for generated mimimalapp
  .changeset/tasty-squids-sin.md
  packages/generator/templates/minimalapp/src/core/layouts/Layout.tsx
Labels: status/in-review

#4050 internal: Publish PRs to npm
  .github/workflows/main.yml
  .github/workflows/pr-release.yml
Labels: status/in-review, no-changeset

#4024 Guard `blitz generate` input against unwanted characters
  .changeset/big-boats-lay.md
  packages/generator/src/generators/model-generator.ts
  packages/generator/src/prisma/field.ts
  packages/generator/src/utils/checkInputOrRaise.ts
  packages/generator/test/generators/utils/checkInputOrRaise.test.ts
  packages/generator/test/prisma/field.test.ts
Labels: status/in-review

#4057 feature: Consolidate mutations schema to schemas.ts file
  .changeset/fast-toys-wash.md
  packages/blitz/src/cli/commands/generate.ts
  packages/generator/src/generators/validations-generator.ts
  packages/generator/src/index.ts
  packages/generator/templates/mutations/create__ModelName__.ts
  packages/generator/templates/mutations/delete__ModelName__.ts
  packages/generator/templates/mutations/update__ModelName__.ts
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/new.tsx
  packages/generator/templates/validations/schemas.ts
Labels: status/in-review
