Repository blitz-js/blitz, pull requests merged in 2023-10, with the labels that each got.

#4222 Update location of `resolve-href` in next 13.5.2
  .changeset/lucky-teachers-sleep.md
  .github/workflows/main.yml
  apps/next13/package.json
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  apps/web/package.json
  integration-tests/auth-with-rpc/package.json
  integration-tests/auth/package.json
  integration-tests/get-initial-props/package.json
  integration-tests/middleware/next-env.d.ts
  integration-tests/middleware/package.json
  integration-tests/middleware/tsconfig.json
  integration-tests/next-13-app-dir/package.json
  integration-tests/no-suspense/package.json
  integration-tests/qm/package.json
  integration-tests/qm/test/use-query.test.tsx
  integration-tests/react-query-utils/next-env.d.ts
  integration-tests/react-query-utils/package.json
  integration-tests/react-query-utils/tsconfig.json
  integration-tests/rpc-path-root/package.json
  integration-tests/rpc/package.json
  integration-tests/trailing-slash/package.json
  integration-tests/utils/blitz-test-utils.tsx
  integration-tests/utils/next-test-utils.ts
  integration-tests/utils/package.json
  package.json
  packages/blitz-auth/package.json
  packages/blitz-next/package.json
  packages/blitz-next/src/index-server.ts
  packages/blitz-rpc/package.json
  pnpm-lock.yaml
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4165 Fix for Tailwind recipe
  .changeset/neat-gorillas-switch.md
  pnpm-lock.yaml
  recipes/tailwind/index.ts
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4176 blitz-next: Fix `next/head` warning in app directory
  .changeset/chatty-scissors-jump.md
  apps/next13/app/auth/layout.tsx
  package.json
  packages/blitz-next/src/error-component.tsx
  packages/blitz-next/src/index-browser.tsx
  pnpm-lock.yaml
Labels: status/in-review, scope/blitz-next

#4225 Authenticate does not work with roles
  .changeset/afraid-ligers-build.md
  integration-tests/auth-with-rpc/src/pages/page-dot-authenticate-role-working.tsx
  integration-tests/auth-with-rpc/src/pages/page-dot-authenticate-role.tsx
  integration-tests/auth-with-rpc/test/index.test.ts
  packages/blitz-auth/src/client/index.tsx
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4228 Recipes: Map Repo link to this repository
  .changeset/pretty-snakes-search.md
  recipes/base-web/index.ts
  recipes/bulma/index.ts
  recipes/bumbag-ui/index.ts
  recipes/chakra-ui/index.ts
  recipes/emotion/index.ts
  recipes/gh-action-yarn-mariadb/index.ts
  recipes/gh-action-yarn-postgres/index.ts
  recipes/ghost/index.ts
  recipes/graphql-apollo-server/index.ts
  recipes/logrocket/index.ts
  recipes/material-ui/index.ts
  recipes/next-ui/index.ts
  recipes/passenger/index.ts
  recipes/reflexjs/index.ts
  recipes/render/index.ts
  recipes/secureheaders/index.ts
  recipes/stitches/index.ts
  recipes/styled-components/index.ts
  recipes/tailwind/index.ts
  recipes/theme-ui/index.ts
  recipes/vanilla-extract/index.ts
Labels: status/in-review

#4237 Upgrade next, prisma and zod to latest versions
  .changeset/green-years-behave.md
  packages/generator/templates/app/package.ts.json
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4235 Remove unintended dependency on next-auth
  .changeset/modern-insects-raise.md
  apps/toolkit-app/next.config.js
  apps/toolkit-app/src/pages/api/auth/[...nextauth].ts
  package.json
  packages/blitz-auth/src/server/adapters/index.ts
  packages/blitz-auth/src/server/adapters/next-auth/adapter.ts
  patches/next-auth@4.18.7.patch
  pnpm-lock.yaml
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️
