Repository blitz-js/blitz, pull requests merged in 2023-02, with the labels that each got.

#4071 Next 13: Remove anchor tags from Link component
  .changeset/swift-glasses-laugh.md
  apps/toolkit-app-passportjs/src/auth/components/LoginForm.tsx
  apps/toolkit-app-passportjs/src/pages/index.tsx
  apps/toolkit-app/src/auth/components/LoginForm.tsx
  packages/generator/templates/app/src/auth/components/LoginForm.tsx
  packages/generator/templates/app/src/pages/index.tsx
  packages/generator/templates/page/__modelIdParam__.tsx
  packages/generator/templates/page/__modelIdParam__/edit.tsx
  packages/generator/templates/page/index.tsx
  packages/generator/templates/page/new.tsx
  recipes/ghost/templates/pages/ghost/index.tsx
Labels: status/in-review

#4067 Add secure-password as an Optional peerDependency
  .changeset/thick-peas-jog.md
  packages/blitz-auth/package.json
  packages/blitz-auth/src/server/auth-utils.ts
  packages/blitz-auth/src/server/index.ts
  packages/blitz-auth/src/server/secure-password.test.ts
  packages/blitz-auth/src/server/secure-password.ts
  packages/generator/templates/app/package.js.json
  packages/generator/templates/app/package.ts.json
  pnpm-lock.yaml
Labels: status/in-review

#4072 Fixing tests for blitz apps that use vitest
  .changeset/plenty-kiwis-greet.md
  apps/toolkit-app/test/index.test.tsx
  integration-tests/middleware/.env
  integration-tests/qm/.env
  integration-tests/rpc/.env
  packages/blitz-rpc/src/data-client/react-query-utils.test.ts
  packages/blitz-rpc/src/data-client/react-query-utils.ts
  packages/blitz/src/errors.ts
  packages/blitz/src/utils/enhance-prisma.ts
  packages/blitz/src/utils/index.ts
  packages/generator/templates/app/test/index.test.tsx
Labels: status/in-review

#4073 docs: delete duplicates of `the` in comments
  apps/toolkit-app/test/index.test.tsx
  packages/generator/templates/app/test/index.test.tsx
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️, no-changeset

#4051 Remove useEffect from reset password templates
  .changeset/perfect-baboons-relate.md
  apps/toolkit-app/src/pages/auth/reset-password.tsx
  packages/generator/templates/app/src/pages/auth/reset-password.tsx
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4082 fix: vulnerabilities in @blitz/auth
  .changeset/strong-chicken-study.md
  packages/blitz-auth/package.json
  pnpm-lock.yaml
Labels: status/in-review, 0 - <(^_^)> - merge it! ✌️

#4062 Update to `"prisma": "4.6.1"`
  .changeset/mean-ears-speak.md
  apps/toolkit-app-passportjs/package.json
  apps/toolkit-app/package.json
  apps/web/package.json
  integration-tests/auth-with-rpc/package.json
  integration-tests/auth/package.json
  integration-tests/get-initial-props/package.json
  integration-tests/no-suspense/package.json
  integration-tests/qm/package.json
  integration-tests/react-query-utils/package.json
  integration-tests/trailing-slash/package.json
  packages/generator/templates/app/package.js.json
  packages/generator/templates/app/package.ts.json
  pnpm-lock.yaml
Labels: status/in-review

#4081 fix: type error in reset-password.tsx
  .changeset/chatty-fireants-leave.md
  packages/generator/templates/app/src/pages/auth/reset-password.tsx
Labels: status/in-review
